/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.parser;

import dplusplus.node.*;
import dplusplus.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTAnswer(@SuppressWarnings("unused") TAnswer node)
    {
        this.index = 0;
    }

    @Override
    public void caseTNumber(@SuppressWarnings("unused") TNumber node)
    {
        this.index = 1;
    }

    @Override
    public void caseTYes(@SuppressWarnings("unused") TYes node)
    {
        this.index = 2;
    }

    @Override
    public void caseTNo(@SuppressWarnings("unused") TNo node)
    {
        this.index = 3;
    }

    @Override
    public void caseTStartBlock(@SuppressWarnings("unused") TStartBlock node)
    {
        this.index = 4;
    }

    @Override
    public void caseTFinishBlock(@SuppressWarnings("unused") TFinishBlock node)
    {
        this.index = 5;
    }

    @Override
    public void caseTInCaseThat(@SuppressWarnings("unused") TInCaseThat node)
    {
        this.index = 6;
    }

    @Override
    public void caseTOtherwise(@SuppressWarnings("unused") TOtherwise node)
    {
        this.index = 7;
    }

    @Override
    public void caseTAsLongAs(@SuppressWarnings("unused") TAsLongAs node)
    {
        this.index = 8;
    }

    @Override
    public void caseTFunction(@SuppressWarnings("unused") TFunction node)
    {
        this.index = 9;
    }

    @Override
    public void caseTProcedure(@SuppressWarnings("unused") TProcedure node)
    {
        this.index = 10;
    }

    @Override
    public void caseTObject(@SuppressWarnings("unused") TObject node)
    {
        this.index = 11;
    }

    @Override
    public void caseTAlterable(@SuppressWarnings("unused") TAlterable node)
    {
        this.index = 12;
    }

    @Override
    public void caseTUnalterable(@SuppressWarnings("unused") TUnalterable node)
    {
        this.index = 13;
    }

    @Override
    public void caseTFamily(@SuppressWarnings("unused") TFamily node)
    {
        this.index = 14;
    }

    @Override
    public void caseTDerivesFrom(@SuppressWarnings("unused") TDerivesFrom node)
    {
        this.index = 15;
    }

    @Override
    public void caseTIf(@SuppressWarnings("unused") TIf node)
    {
        this.index = 16;
    }

    @Override
    public void caseTElse(@SuppressWarnings("unused") TElse node)
    {
        this.index = 17;
    }

    @Override
    public void caseTSoma(@SuppressWarnings("unused") TSoma node)
    {
        this.index = 18;
    }

    @Override
    public void caseTSubtracao(@SuppressWarnings("unused") TSubtracao node)
    {
        this.index = 19;
    }

    @Override
    public void caseTMultiplicacao(@SuppressWarnings("unused") TMultiplicacao node)
    {
        this.index = 20;
    }

    @Override
    public void caseTDivisao(@SuppressWarnings("unused") TDivisao node)
    {
        this.index = 21;
    }

    @Override
    public void caseTIgual(@SuppressWarnings("unused") TIgual node)
    {
        this.index = 22;
    }

    @Override
    public void caseTMenorQue(@SuppressWarnings("unused") TMenorQue node)
    {
        this.index = 23;
    }

    @Override
    public void caseTMaiorQue(@SuppressWarnings("unused") TMaiorQue node)
    {
        this.index = 24;
    }

    @Override
    public void caseTNegacao(@SuppressWarnings("unused") TNegacao node)
    {
        this.index = 25;
    }

    @Override
    public void caseTELogico(@SuppressWarnings("unused") TELogico node)
    {
        this.index = 26;
    }

    @Override
    public void caseTOuLogico(@SuppressWarnings("unused") TOuLogico node)
    {
        this.index = 27;
    }

    @Override
    public void caseTPonto(@SuppressWarnings("unused") TPonto node)
    {
        this.index = 28;
    }

    @Override
    public void caseTSetaAcesso(@SuppressWarnings("unused") TSetaAcesso node)
    {
        this.index = 29;
    }

    @Override
    public void caseTAtribuicao(@SuppressWarnings("unused") TAtribuicao node)
    {
        this.index = 30;
    }

    @Override
    public void caseTPontoEntrada(@SuppressWarnings("unused") TPontoEntrada node)
    {
        this.index = 31;
    }

    @Override
    public void caseTColcheteEsq(@SuppressWarnings("unused") TColcheteEsq node)
    {
        this.index = 32;
    }

    @Override
    public void caseTColcheteDir(@SuppressWarnings("unused") TColcheteDir node)
    {
        this.index = 33;
    }

    @Override
    public void caseTParenteseEsq(@SuppressWarnings("unused") TParenteseEsq node)
    {
        this.index = 34;
    }

    @Override
    public void caseTParenteseDir(@SuppressWarnings("unused") TParenteseDir node)
    {
        this.index = 35;
    }

    @Override
    public void caseTPipe(@SuppressWarnings("unused") TPipe node)
    {
        this.index = 36;
    }

    @Override
    public void caseTAmpersand(@SuppressWarnings("unused") TAmpersand node)
    {
        this.index = 37;
    }

    @Override
    public void caseTValorInteiro(@SuppressWarnings("unused") TValorInteiro node)
    {
        this.index = 38;
    }

    @Override
    public void caseTValorReal(@SuppressWarnings("unused") TValorReal node)
    {
        this.index = 39;
    }

    @Override
    public void caseTId(@SuppressWarnings("unused") TId node)
    {
        this.index = 40;
    }

    @Override
    public void caseTIdClasse(@SuppressWarnings("unused") TIdClasse node)
    {
        this.index = 41;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 42;
    }
}
