/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.lexer;

import java.io.*;
import dplusplus.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAnswer(line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumber(line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TYes(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNo(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStartBlock(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFinishBlock(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInCaseThat(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOtherwise(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAsLongAs(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFunction(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TProcedure(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TObject(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAlterable(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TUnalterable(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFamily(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDerivesFrom(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIf(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TElse(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSoma(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSubtracao(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMultiplicacao(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDivisao(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIgual(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenorQue(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMaiorQue(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNegacao(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TELogico(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOuLogico(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPonto(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAtribuicao(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPontoEntrada(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColcheteEsq(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColcheteDir(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TParenteseEsq(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TParenteseDir(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPipe(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAmpersand(line, pos); }
    Token new37(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TValorInteiro(text, line, pos); }
    Token new38(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TValorReal(text, line, pos); }
    Token new39(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TId(text, line, pos); }
    Token new40(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdClasse(text, line, pos); }
    Token new41(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioLinha(text, line, pos); }
    Token new42(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioBloco(text, line, pos); }
    Token new43(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEspacoVazio(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {33, 33, 5}, {38, 38, 6}, {40, 40, 7}, {41, 41, 8}, {42, 42, 9}, {43, 43, 10}, {45, 45, 11}, {46, 46, 12}, {47, 47, 13}, {48, 57, 14}, {60, 60, 15}, {61, 61, 16}, {62, 62, 17}, {65, 90, 18}, {91, 91, 19}, {93, 93, 20}, {97, 97, 21}, {98, 99, 22}, {100, 100, 23}, {101, 101, 24}, {102, 102, 25}, {103, 104, 22}, {105, 105, 26}, {106, 109, 22}, {110, 110, 27}, {111, 111, 28}, {112, 112, 29}, {113, 114, 22}, {115, 115, 30}, {116, 116, 22}, {117, 117, 31}, {118, 120, 22}, {121, 121, 32}, {122, 122, 22}, {123, 123, 33}, {124, 124, 34}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 9, 1}, {10, 10, 35}, {13, 32, -2}, },
            {{9, 32, -2}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {{45, 45, 36}, },
            {},
            {},
            {{46, 46, 37}, {48, 57, 14}, },
            {{60, 60, 38}, },
            {},
            {{62, 62, 39}, },
            {{65, 90, 40}, {95, 95, 41}, {97, 122, 42}, },
            {},
            {},
            {{65, 90, 43}, {95, 95, 44}, {97, 107, 45}, {108, 108, 46}, {109, 109, 45}, {110, 110, 47}, {111, 114, 45}, {115, 115, 48}, {116, 122, 45}, },
            {{65, 95, -23}, {97, 122, 45}, },
            {{65, 95, -23}, {97, 100, 45}, {101, 101, 49}, {102, 122, 45}, },
            {{65, 107, -23}, {108, 108, 50}, {109, 122, 45}, },
            {{65, 95, -23}, {97, 97, 51}, {98, 104, 45}, {105, 105, 52}, {106, 116, 45}, {117, 117, 53}, {118, 122, 45}, },
            {{65, 95, -23}, {97, 101, 45}, {102, 102, 54}, {103, 109, 45}, {110, 110, 55}, {111, 122, 45}, },
            {{65, 95, -23}, {97, 110, 45}, {111, 111, 56}, {112, 116, 45}, {117, 117, 57}, {118, 122, 45}, },
            {{65, 95, -23}, {97, 97, 45}, {98, 98, 58}, {99, 113, 45}, {114, 114, 59}, {115, 115, 45}, {116, 116, 60}, {117, 122, 45}, },
            {{65, 95, -23}, {97, 113, 45}, {114, 114, 61}, {115, 122, 45}, },
            {{65, 95, -23}, {97, 115, 45}, {116, 116, 62}, {117, 122, 45}, },
            {{65, 95, -23}, {97, 109, 45}, {110, 110, 63}, {111, 122, 45}, },
            {{65, 100, -25}, {101, 101, 64}, {102, 122, 45}, },
            {{45, 45, 65}, },
            {},
            {{9, 32, -2}, },
            {{0, 9, 66}, {10, 10, 67}, {11, 12, 66}, {13, 13, 68}, {14, 65535, 66}, },
            {{48, 57, 69}, },
            {},
            {},
            {{65, 122, -20}, },
            {{65, 122, -20}, },
            {{65, 122, -20}, },
            {{65, 122, -24}, },
            {{65, 122, -24}, },
            {{65, 122, -24}, },
            {{65, 115, -32}, {116, 116, 70}, {117, 122, 45}, },
            {{65, 95, -23}, {97, 99, 45}, {100, 100, 71}, {101, 114, 45}, {115, 115, 72}, {116, 122, 45}, },
            {{32, 32, 73}, {65, 122, -24}, },
            {{65, 113, -31}, {114, 114, 74}, {115, 122, 45}, },
            {{65, 95, -23}, {97, 114, 45}, {115, 115, 75}, {116, 122, 45}, },
            {{65, 95, -23}, {97, 108, 45}, {109, 109, 76}, {110, 122, 45}, },
            {{65, 109, -33}, {110, 110, 77}, {111, 122, 45}, },
            {{65, 109, -33}, {110, 110, 78}, {111, 122, 45}, },
            {{65, 122, -24}, },
            {{32, 32, 79}, {65, 122, -24}, },
            {{65, 122, -24}, },
            {{65, 108, -53}, {109, 109, 80}, {110, 122, 45}, },
            {{65, 95, -23}, {97, 105, 45}, {106, 106, 81}, {107, 122, 45}, },
            {{65, 122, -24}, },
            {{65, 95, -23}, {97, 103, 45}, {104, 104, 82}, {105, 122, 45}, },
            {{65, 110, -29}, {111, 111, 83}, {112, 122, 45}, },
            {{65, 95, -23}, {97, 97, 84}, {98, 122, 45}, },
            {{65, 95, -23}, {97, 97, 85}, {98, 122, 45}, },
            {{65, 114, -52}, {115, 115, 86}, {116, 122, 45}, },
            {{0, 44, 87}, {45, 45, 88}, {46, 65535, 87}, },
            {{0, 65535, -38}, },
            {},
            {{10, 10, 89}, },
            {{48, 57, 69}, },
            {{65, 100, -25}, {101, 101, 90}, {102, 122, 45}, },
            {{65, 122, -24}, },
            {{65, 95, -23}, {97, 118, 45}, {119, 119, 91}, {120, 122, 45}, },
            {{108, 108, 92}, },
            {{65, 95, -23}, {97, 104, 45}, {105, 105, 93}, {106, 122, 45}, },
            {{65, 100, -25}, {101, 101, 94}, {102, 122, 45}, },
            {{65, 104, -76}, {105, 105, 95}, {106, 122, 45}, },
            {{65, 104, -76}, {105, 105, 96}, {106, 122, 45}, },
            {{65, 95, -23}, {97, 98, 45}, {99, 99, 97}, {100, 122, 45}, },
            {{99, 99, 98}, },
            {{65, 97, -30}, {98, 98, 99}, {99, 122, 45}, },
            {{65, 100, -25}, {101, 101, 100}, {102, 122, 45}, },
            {{65, 100, -25}, {101, 101, 101}, {102, 122, 45}, },
            {{65, 98, -80}, {99, 99, 102}, {100, 122, 45}, },
            {{65, 113, -31}, {114, 114, 103}, {115, 122, 45}, },
            {{65, 107, -23}, {108, 108, 104}, {109, 122, 45}, },
            {{65, 122, -24}, },
            {{0, 65535, -67}, },
            {{0, 44, 105}, {45, 45, 88}, {46, 124, 105}, {125, 125, 106}, {126, 65535, 105}, },
            {},
            {{65, 113, -31}, {114, 114, 107}, {115, 122, 45}, },
            {{65, 100, -25}, {101, 101, 108}, {102, 122, 45}, },
            {{111, 111, 109}, },
            {{65, 95, -23}, {97, 117, 45}, {118, 118, 110}, {119, 122, 45}, },
            {{65, 122, -24}, },
            {{65, 107, -23}, {108, 108, 111}, {109, 122, 45}, },
            {{65, 114, -52}, {115, 115, 112}, {116, 122, 45}, },
            {{65, 115, -32}, {116, 116, 113}, {117, 122, 45}, },
            {{97, 97, 114}, },
            {{65, 100, -25}, {101, 101, 115}, {102, 122, 45}, },
            {{65, 98, -80}, {99, 99, 116}, {100, 122, 45}, },
            {{65, 113, -31}, {114, 114, 117}, {115, 122, 45}, },
            {{65, 100, -25}, {101, 101, 118}, {102, 122, 45}, },
            {{65, 115, -32}, {116, 116, 119}, {117, 122, 45}, },
            {{65, 115, -32}, {116, 116, 120}, {117, 122, 45}, },
            {{0, 44, 121}, {45, 45, 122}, {46, 65535, 121}, },
            {},
            {{65, 95, -23}, {97, 97, 123}, {98, 122, 45}, },
            {{65, 113, -31}, {114, 114, 124}, {115, 122, 45}, },
            {{110, 110, 125}, },
            {{65, 100, -25}, {101, 101, 126}, {102, 122, 45}, },
            {{65, 95, -23}, {97, 120, 45}, {121, 121, 127}, {122, 122, 45}, },
            {{65, 103, -62}, {104, 104, 128}, {105, 122, 45}, },
            {{65, 104, -76}, {105, 105, 129}, {106, 122, 45}, },
            {{115, 115, 130}, },
            {{65, 113, -31}, {114, 114, 131}, {115, 122, 45}, },
            {{65, 115, -32}, {116, 116, 132}, {117, 122, 45}, },
            {{65, 118, -74}, {119, 119, 133}, {120, 122, 45}, },
            {{65, 99, -49}, {100, 100, 134}, {101, 122, 45}, },
            {{65, 122, -24}, },
            {{65, 100, -25}, {101, 101, 135}, {102, 122, 45}, },
            {{0, 65535, -107}, },
            {{0, 44, 105}, {45, 45, 122}, {46, 65535, -90}, },
            {{65, 97, -30}, {98, 98, 136}, {99, 122, 45}, },
            {{65, 122, -24}, },
            {{103, 103, 137}, },
            {{65, 114, -52}, {115, 115, 138}, {116, 122, 45}, },
            {{65, 122, -24}, },
            {{65, 122, -24}, },
            {{65, 110, -29}, {111, 111, 139}, {112, 122, 45}, },
            {{101, 101, 140}, },
            {{65, 122, -24}, },
            {{65, 122, -24}, },
            {{65, 104, -76}, {105, 105, 141}, {106, 122, 45}, },
            {{65, 95, -23}, {97, 116, 45}, {117, 117, 142}, {118, 122, 45}, },
            {{65, 113, -31}, {114, 114, 143}, {115, 122, 45}, },
            {{65, 107, -23}, {108, 108, 144}, {109, 122, 45}, },
            {{32, 32, 145}, },
            {{32, 32, 146}, {65, 122, -24}, },
            {{65, 109, -33}, {110, 110, 147}, {111, 122, 45}, },
            {{32, 32, 148}, },
            {{65, 114, -52}, {115, 115, 149}, {116, 122, 45}, },
            {{65, 113, -31}, {114, 114, 150}, {115, 122, 45}, },
            {{65, 95, -23}, {97, 97, 151}, {98, 122, 45}, },
            {{65, 100, -25}, {101, 101, 152}, {102, 122, 45}, },
            {{97, 97, 153}, },
            {{102, 102, 154}, },
            {{65, 122, -24}, },
            {{116, 116, 155}, },
            {{65, 100, -25}, {101, 101, 156}, {102, 122, 45}, },
            {{65, 100, -25}, {101, 101, 157}, {102, 122, 45}, },
            {{65, 97, -30}, {98, 98, 158}, {99, 122, 45}, },
            {{65, 122, -24}, },
            {{115, 115, 159}, },
            {{114, 114, 160}, },
            {{104, 104, 161}, },
            {{65, 122, -24}, },
            {{65, 122, -24}, },
            {{65, 107, -23}, {108, 108, 162}, {109, 122, 45}, },
            {},
            {{111, 111, 163}, },
            {{97, 97, 164}, },
            {{65, 100, -25}, {101, 101, 165}, {102, 122, 45}, },
            {{109, 109, 166}, },
            {{116, 116, 167}, },
            {{65, 122, -24}, },
            {},
            {},
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 43, 43, 43, 43, 25, 36, 33, 34, 20, 18, 19, 28, 21, 37, 23, 22, 24, 40, 31, 32, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, -1, 35, 43, 41, -1, 29, 30, 40, 40, 40, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 16, 39, 3, 39, 39, 27, 39, 39, 39, 39, 39, -1, 41, 41, 41, 38, 39, 26, 39, -1, 39, 39, 39, 39, 39, -1, 39, 39, 39, 39, 39, 39, 2, -1, -1, 41, 39, 39, -1, 39, 17, 39, 39, 39, -1, 39, 39, 39, 39, 39, 39, -1, 42, 39, 39, -1, 39, 39, 39, 39, -1, 39, 39, 39, 39, 4, 39, -1, -1, 39, 0, -1, 39, 14, 5, 39, -1, 1, 11, 39, 39, 39, 39, -1, 39, 39, -1, 39, 39, 39, 39, -1, -1, 9, -1, 39, 39, 39, 12, -1, -1, -1, 7, 10, 39, 8, -1, -1, 39, -1, -1, 13, 15, 6, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
