/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AAbertoComando extends PComando
{
    private PComandoAberto _comandoAberto_;

    public AAbertoComando()
    {
        // Constructor
    }

    public AAbertoComando(
        @SuppressWarnings("hiding") PComandoAberto _comandoAberto_)
    {
        // Constructor
        setComandoAberto(_comandoAberto_);

    }

    @Override
    public Object clone()
    {
        return new AAbertoComando(
            cloneNode(this._comandoAberto_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAbertoComando(this);
    }

    public PComandoAberto getComandoAberto()
    {
        return this._comandoAberto_;
    }

    public void setComandoAberto(PComandoAberto node)
    {
        if(this._comandoAberto_ != null)
        {
            this._comandoAberto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoAberto_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comandoAberto_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comandoAberto_ == child)
        {
            this._comandoAberto_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comandoAberto_ == oldChild)
        {
            setComandoAberto((PComandoAberto) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
