/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import java.util.*;
import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AAcesso extends PAcesso
{
    private TId _id_;
    private final LinkedList<PAcessoExtra> _acessoExtra_ = new LinkedList<PAcessoExtra>();

    public AAcesso()
    {
        // Constructor
    }

    public AAcesso(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") List<?> _acessoExtra_)
    {
        // Constructor
        setId(_id_);

        setAcessoExtra(_acessoExtra_);

    }

    @Override
    public Object clone()
    {
        return new AAcesso(
            cloneNode(this._id_),
            cloneList(this._acessoExtra_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAcesso(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public LinkedList<PAcessoExtra> getAcessoExtra()
    {
        return this._acessoExtra_;
    }

    public void setAcessoExtra(List<?> list)
    {
        for(PAcessoExtra e : this._acessoExtra_)
        {
            e.parent(null);
        }
        this._acessoExtra_.clear();

        for(Object obj_e : list)
        {
            PAcessoExtra e = (PAcessoExtra) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._acessoExtra_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._acessoExtra_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._acessoExtra_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        for(ListIterator<PAcessoExtra> i = this._acessoExtra_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAcessoExtra) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
