/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AAcessoExtra extends PAcessoExtra
{
    private TSetaAcesso _setaAcesso_;
    private TId _id_;

    public AAcessoExtra()
    {
        // Constructor
    }

    public AAcessoExtra(
        @SuppressWarnings("hiding") TSetaAcesso _setaAcesso_,
        @SuppressWarnings("hiding") TId _id_)
    {
        // Constructor
        setSetaAcesso(_setaAcesso_);

        setId(_id_);

    }

    @Override
    public Object clone()
    {
        return new AAcessoExtra(
            cloneNode(this._setaAcesso_),
            cloneNode(this._id_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAcessoExtra(this);
    }

    public TSetaAcesso getSetaAcesso()
    {
        return this._setaAcesso_;
    }

    public void setSetaAcesso(TSetaAcesso node)
    {
        if(this._setaAcesso_ != null)
        {
            this._setaAcesso_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._setaAcesso_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._setaAcesso_)
            + toString(this._id_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._setaAcesso_ == child)
        {
            this._setaAcesso_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._setaAcesso_ == oldChild)
        {
            setSetaAcesso((TSetaAcesso) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
