/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ABlocoExp extends PBlocoExp
{
    private TStartBlock _startBlock_;
    private PAtributos _atributos_;
    private PExp _exp_;
    private TFinishBlock _finishBlock_;

    public ABlocoExp()
    {
        // Constructor
    }

    public ABlocoExp(
        @SuppressWarnings("hiding") TStartBlock _startBlock_,
        @SuppressWarnings("hiding") PAtributos _atributos_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TFinishBlock _finishBlock_)
    {
        // Constructor
        setStartBlock(_startBlock_);

        setAtributos(_atributos_);

        setExp(_exp_);

        setFinishBlock(_finishBlock_);

    }

    @Override
    public Object clone()
    {
        return new ABlocoExp(
            cloneNode(this._startBlock_),
            cloneNode(this._atributos_),
            cloneNode(this._exp_),
            cloneNode(this._finishBlock_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABlocoExp(this);
    }

    public TStartBlock getStartBlock()
    {
        return this._startBlock_;
    }

    public void setStartBlock(TStartBlock node)
    {
        if(this._startBlock_ != null)
        {
            this._startBlock_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._startBlock_ = node;
    }

    public PAtributos getAtributos()
    {
        return this._atributos_;
    }

    public void setAtributos(PAtributos node)
    {
        if(this._atributos_ != null)
        {
            this._atributos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atributos_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TFinishBlock getFinishBlock()
    {
        return this._finishBlock_;
    }

    public void setFinishBlock(TFinishBlock node)
    {
        if(this._finishBlock_ != null)
        {
            this._finishBlock_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._finishBlock_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._startBlock_)
            + toString(this._atributos_)
            + toString(this._exp_)
            + toString(this._finishBlock_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._startBlock_ == child)
        {
            this._startBlock_ = null;
            return;
        }

        if(this._atributos_ == child)
        {
            this._atributos_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._finishBlock_ == child)
        {
            this._finishBlock_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._startBlock_ == oldChild)
        {
            setStartBlock((TStartBlock) newChild);
            return;
        }

        if(this._atributos_ == oldChild)
        {
            setAtributos((PAtributos) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._finishBlock_ == oldChild)
        {
            setFinishBlock((TFinishBlock) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
