/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ABloco extends PBloco
{
    private TStartBlock _startBlock_;
    private PAtributos _atributos_;
    private PListaComandos _listaComandos_;
    private TFinishBlock _finishBlock_;

    public ABloco()
    {
        // Constructor
    }

    public ABloco(
        @SuppressWarnings("hiding") TStartBlock _startBlock_,
        @SuppressWarnings("hiding") PAtributos _atributos_,
        @SuppressWarnings("hiding") PListaComandos _listaComandos_,
        @SuppressWarnings("hiding") TFinishBlock _finishBlock_)
    {
        // Constructor
        setStartBlock(_startBlock_);

        setAtributos(_atributos_);

        setListaComandos(_listaComandos_);

        setFinishBlock(_finishBlock_);

    }

    @Override
    public Object clone()
    {
        return new ABloco(
            cloneNode(this._startBlock_),
            cloneNode(this._atributos_),
            cloneNode(this._listaComandos_),
            cloneNode(this._finishBlock_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABloco(this);
    }

    public TStartBlock getStartBlock()
    {
        return this._startBlock_;
    }

    public void setStartBlock(TStartBlock node)
    {
        if(this._startBlock_ != null)
        {
            this._startBlock_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._startBlock_ = node;
    }

    public PAtributos getAtributos()
    {
        return this._atributos_;
    }

    public void setAtributos(PAtributos node)
    {
        if(this._atributos_ != null)
        {
            this._atributos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atributos_ = node;
    }

    public PListaComandos getListaComandos()
    {
        return this._listaComandos_;
    }

    public void setListaComandos(PListaComandos node)
    {
        if(this._listaComandos_ != null)
        {
            this._listaComandos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaComandos_ = node;
    }

    public TFinishBlock getFinishBlock()
    {
        return this._finishBlock_;
    }

    public void setFinishBlock(TFinishBlock node)
    {
        if(this._finishBlock_ != null)
        {
            this._finishBlock_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._finishBlock_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._startBlock_)
            + toString(this._atributos_)
            + toString(this._listaComandos_)
            + toString(this._finishBlock_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._startBlock_ == child)
        {
            this._startBlock_ = null;
            return;
        }

        if(this._atributos_ == child)
        {
            this._atributos_ = null;
            return;
        }

        if(this._listaComandos_ == child)
        {
            this._listaComandos_ = null;
            return;
        }

        if(this._finishBlock_ == child)
        {
            this._finishBlock_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._startBlock_ == oldChild)
        {
            setStartBlock((TStartBlock) newChild);
            return;
        }

        if(this._atributos_ == oldChild)
        {
            setAtributos((PAtributos) newChild);
            return;
        }

        if(this._listaComandos_ == oldChild)
        {
            setListaComandos((PListaComandos) newChild);
            return;
        }

        if(this._finishBlock_ == oldChild)
        {
            setFinishBlock((TFinishBlock) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
