/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import java.util.*;
import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AChamada extends PChamada
{
    private TId _base_;
    private final LinkedList<TId> _acessos_ = new LinkedList<TId>();
    private final LinkedList<PExp> _argumentos_ = new LinkedList<PExp>();

    public AChamada()
    {
        // Constructor
    }

    public AChamada(
        @SuppressWarnings("hiding") TId _base_,
        @SuppressWarnings("hiding") List<?> _acessos_,
        @SuppressWarnings("hiding") List<?> _argumentos_)
    {
        // Constructor
        setBase(_base_);

        setAcessos(_acessos_);

        setArgumentos(_argumentos_);

    }

    @Override
    public Object clone()
    {
        return new AChamada(
            cloneNode(this._base_),
            cloneList(this._acessos_),
            cloneList(this._argumentos_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAChamada(this);
    }

    public TId getBase()
    {
        return this._base_;
    }

    public void setBase(TId node)
    {
        if(this._base_ != null)
        {
            this._base_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._base_ = node;
    }

    public LinkedList<TId> getAcessos()
    {
        return this._acessos_;
    }

    public void setAcessos(List<?> list)
    {
        for(TId e : this._acessos_)
        {
            e.parent(null);
        }
        this._acessos_.clear();

        for(Object obj_e : list)
        {
            TId e = (TId) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._acessos_.add(e);
        }
    }

    public LinkedList<PExp> getArgumentos()
    {
        return this._argumentos_;
    }

    public void setArgumentos(List<?> list)
    {
        for(PExp e : this._argumentos_)
        {
            e.parent(null);
        }
        this._argumentos_.clear();

        for(Object obj_e : list)
        {
            PExp e = (PExp) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._argumentos_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._base_)
            + toString(this._acessos_)
            + toString(this._argumentos_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._base_ == child)
        {
            this._base_ = null;
            return;
        }

        if(this._acessos_.remove(child))
        {
            return;
        }

        if(this._argumentos_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._base_ == oldChild)
        {
            setBase((TId) newChild);
            return;
        }

        for(ListIterator<TId> i = this._acessos_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((TId) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator<PExp> i = this._argumentos_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExp) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
