/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AComComandoDecProcedimento extends PDecProcedimento
{
    private TPontoEntrada _pontoEntrada_;
    private TProcedure _procedure_;
    private TId _id_;
    private TColcheteEsq _colcheteEsq_;
    private PListaParametros _listaParametros_;
    private TColcheteDir _colcheteDir_;
    private PComando _comando_;

    public AComComandoDecProcedimento()
    {
        // Constructor
    }

    public AComComandoDecProcedimento(
        @SuppressWarnings("hiding") TPontoEntrada _pontoEntrada_,
        @SuppressWarnings("hiding") TProcedure _procedure_,
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TColcheteEsq _colcheteEsq_,
        @SuppressWarnings("hiding") PListaParametros _listaParametros_,
        @SuppressWarnings("hiding") TColcheteDir _colcheteDir_,
        @SuppressWarnings("hiding") PComando _comando_)
    {
        // Constructor
        setPontoEntrada(_pontoEntrada_);

        setProcedure(_procedure_);

        setId(_id_);

        setColcheteEsq(_colcheteEsq_);

        setListaParametros(_listaParametros_);

        setColcheteDir(_colcheteDir_);

        setComando(_comando_);

    }

    @Override
    public Object clone()
    {
        return new AComComandoDecProcedimento(
            cloneNode(this._pontoEntrada_),
            cloneNode(this._procedure_),
            cloneNode(this._id_),
            cloneNode(this._colcheteEsq_),
            cloneNode(this._listaParametros_),
            cloneNode(this._colcheteDir_),
            cloneNode(this._comando_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComComandoDecProcedimento(this);
    }

    public TPontoEntrada getPontoEntrada()
    {
        return this._pontoEntrada_;
    }

    public void setPontoEntrada(TPontoEntrada node)
    {
        if(this._pontoEntrada_ != null)
        {
            this._pontoEntrada_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontoEntrada_ = node;
    }

    public TProcedure getProcedure()
    {
        return this._procedure_;
    }

    public void setProcedure(TProcedure node)
    {
        if(this._procedure_ != null)
        {
            this._procedure_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._procedure_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TColcheteEsq getColcheteEsq()
    {
        return this._colcheteEsq_;
    }

    public void setColcheteEsq(TColcheteEsq node)
    {
        if(this._colcheteEsq_ != null)
        {
            this._colcheteEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colcheteEsq_ = node;
    }

    public PListaParametros getListaParametros()
    {
        return this._listaParametros_;
    }

    public void setListaParametros(PListaParametros node)
    {
        if(this._listaParametros_ != null)
        {
            this._listaParametros_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaParametros_ = node;
    }

    public TColcheteDir getColcheteDir()
    {
        return this._colcheteDir_;
    }

    public void setColcheteDir(TColcheteDir node)
    {
        if(this._colcheteDir_ != null)
        {
            this._colcheteDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colcheteDir_ = node;
    }

    public PComando getComando()
    {
        return this._comando_;
    }

    public void setComando(PComando node)
    {
        if(this._comando_ != null)
        {
            this._comando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comando_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pontoEntrada_)
            + toString(this._procedure_)
            + toString(this._id_)
            + toString(this._colcheteEsq_)
            + toString(this._listaParametros_)
            + toString(this._colcheteDir_)
            + toString(this._comando_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pontoEntrada_ == child)
        {
            this._pontoEntrada_ = null;
            return;
        }

        if(this._procedure_ == child)
        {
            this._procedure_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._colcheteEsq_ == child)
        {
            this._colcheteEsq_ = null;
            return;
        }

        if(this._listaParametros_ == child)
        {
            this._listaParametros_ = null;
            return;
        }

        if(this._colcheteDir_ == child)
        {
            this._colcheteDir_ = null;
            return;
        }

        if(this._comando_ == child)
        {
            this._comando_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pontoEntrada_ == oldChild)
        {
            setPontoEntrada((TPontoEntrada) newChild);
            return;
        }

        if(this._procedure_ == oldChild)
        {
            setProcedure((TProcedure) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._colcheteEsq_ == oldChild)
        {
            setColcheteEsq((TColcheteEsq) newChild);
            return;
        }

        if(this._listaParametros_ == oldChild)
        {
            setListaParametros((PListaParametros) newChild);
            return;
        }

        if(this._colcheteDir_ == oldChild)
        {
            setColcheteDir((TColcheteDir) newChild);
            return;
        }

        if(this._comando_ == oldChild)
        {
            setComando((PComando) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
