/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AComandoVazio extends PComandoVazio
{
    private TStartBlock _startBlock_;
    private TFinishBlock _finishBlock_;
    private TPonto _ponto_;

    public AComandoVazio()
    {
        // Constructor
    }

    public AComandoVazio(
        @SuppressWarnings("hiding") TStartBlock _startBlock_,
        @SuppressWarnings("hiding") TFinishBlock _finishBlock_,
        @SuppressWarnings("hiding") TPonto _ponto_)
    {
        // Constructor
        setStartBlock(_startBlock_);

        setFinishBlock(_finishBlock_);

        setPonto(_ponto_);

    }

    @Override
    public Object clone()
    {
        return new AComandoVazio(
            cloneNode(this._startBlock_),
            cloneNode(this._finishBlock_),
            cloneNode(this._ponto_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComandoVazio(this);
    }

    public TStartBlock getStartBlock()
    {
        return this._startBlock_;
    }

    public void setStartBlock(TStartBlock node)
    {
        if(this._startBlock_ != null)
        {
            this._startBlock_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._startBlock_ = node;
    }

    public TFinishBlock getFinishBlock()
    {
        return this._finishBlock_;
    }

    public void setFinishBlock(TFinishBlock node)
    {
        if(this._finishBlock_ != null)
        {
            this._finishBlock_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._finishBlock_ = node;
    }

    public TPonto getPonto()
    {
        return this._ponto_;
    }

    public void setPonto(TPonto node)
    {
        if(this._ponto_ != null)
        {
            this._ponto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ponto_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._startBlock_)
            + toString(this._finishBlock_)
            + toString(this._ponto_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._startBlock_ == child)
        {
            this._startBlock_ = null;
            return;
        }

        if(this._finishBlock_ == child)
        {
            this._finishBlock_ = null;
            return;
        }

        if(this._ponto_ == child)
        {
            this._ponto_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._startBlock_ == oldChild)
        {
            setStartBlock((TStartBlock) newChild);
            return;
        }

        if(this._finishBlock_ == oldChild)
        {
            setFinishBlock((TFinishBlock) newChild);
            return;
        }

        if(this._ponto_ == oldChild)
        {
            setPonto((TPonto) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
