/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ACondicionalComando extends PComando
{
    private PExp _exp_;
    private PComando _comandoIf_;
    private PComando _comandoElse_;

    public ACondicionalComando()
    {
        // Constructor
    }

    public ACondicionalComando(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") PComando _comandoIf_,
        @SuppressWarnings("hiding") PComando _comandoElse_)
    {
        // Constructor
        setExp(_exp_);

        setComandoIf(_comandoIf_);

        setComandoElse(_comandoElse_);

    }

    @Override
    public Object clone()
    {
        return new ACondicionalComando(
            cloneNode(this._exp_),
            cloneNode(this._comandoIf_),
            cloneNode(this._comandoElse_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACondicionalComando(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public PComando getComandoIf()
    {
        return this._comandoIf_;
    }

    public void setComandoIf(PComando node)
    {
        if(this._comandoIf_ != null)
        {
            this._comandoIf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoIf_ = node;
    }

    public PComando getComandoElse()
    {
        return this._comandoElse_;
    }

    public void setComandoElse(PComando node)
    {
        if(this._comandoElse_ != null)
        {
            this._comandoElse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoElse_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._comandoIf_)
            + toString(this._comandoElse_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._comandoIf_ == child)
        {
            this._comandoIf_ = null;
            return;
        }

        if(this._comandoElse_ == child)
        {
            this._comandoElse_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._comandoIf_ == oldChild)
        {
            setComandoIf((PComando) newChild);
            return;
        }

        if(this._comandoElse_ == oldChild)
        {
            setComandoElse((PComando) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
