/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ACondicionalElseComando extends PComando
{
    private TInCaseThat _inCaseThat_;
    private TParenteseEsq _parenteseEsq_;
    private PExp _exp_;
    private TParenteseDir _parenteseDir_;
    private PComando _comandoIf_;
    private TOtherwise _otherwise_;
    private PComando _comandoElse_;

    public ACondicionalElseComando()
    {
        // Constructor
    }

    public ACondicionalElseComando(
        @SuppressWarnings("hiding") TInCaseThat _inCaseThat_,
        @SuppressWarnings("hiding") TParenteseEsq _parenteseEsq_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TParenteseDir _parenteseDir_,
        @SuppressWarnings("hiding") PComando _comandoIf_,
        @SuppressWarnings("hiding") TOtherwise _otherwise_,
        @SuppressWarnings("hiding") PComando _comandoElse_)
    {
        // Constructor
        setInCaseThat(_inCaseThat_);

        setParenteseEsq(_parenteseEsq_);

        setExp(_exp_);

        setParenteseDir(_parenteseDir_);

        setComandoIf(_comandoIf_);

        setOtherwise(_otherwise_);

        setComandoElse(_comandoElse_);

    }

    @Override
    public Object clone()
    {
        return new ACondicionalElseComando(
            cloneNode(this._inCaseThat_),
            cloneNode(this._parenteseEsq_),
            cloneNode(this._exp_),
            cloneNode(this._parenteseDir_),
            cloneNode(this._comandoIf_),
            cloneNode(this._otherwise_),
            cloneNode(this._comandoElse_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACondicionalElseComando(this);
    }

    public TInCaseThat getInCaseThat()
    {
        return this._inCaseThat_;
    }

    public void setInCaseThat(TInCaseThat node)
    {
        if(this._inCaseThat_ != null)
        {
            this._inCaseThat_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inCaseThat_ = node;
    }

    public TParenteseEsq getParenteseEsq()
    {
        return this._parenteseEsq_;
    }

    public void setParenteseEsq(TParenteseEsq node)
    {
        if(this._parenteseEsq_ != null)
        {
            this._parenteseEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parenteseEsq_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TParenteseDir getParenteseDir()
    {
        return this._parenteseDir_;
    }

    public void setParenteseDir(TParenteseDir node)
    {
        if(this._parenteseDir_ != null)
        {
            this._parenteseDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parenteseDir_ = node;
    }

    public PComando getComandoIf()
    {
        return this._comandoIf_;
    }

    public void setComandoIf(PComando node)
    {
        if(this._comandoIf_ != null)
        {
            this._comandoIf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoIf_ = node;
    }

    public TOtherwise getOtherwise()
    {
        return this._otherwise_;
    }

    public void setOtherwise(TOtherwise node)
    {
        if(this._otherwise_ != null)
        {
            this._otherwise_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._otherwise_ = node;
    }

    public PComando getComandoElse()
    {
        return this._comandoElse_;
    }

    public void setComandoElse(PComando node)
    {
        if(this._comandoElse_ != null)
        {
            this._comandoElse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoElse_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._inCaseThat_)
            + toString(this._parenteseEsq_)
            + toString(this._exp_)
            + toString(this._parenteseDir_)
            + toString(this._comandoIf_)
            + toString(this._otherwise_)
            + toString(this._comandoElse_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._inCaseThat_ == child)
        {
            this._inCaseThat_ = null;
            return;
        }

        if(this._parenteseEsq_ == child)
        {
            this._parenteseEsq_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._parenteseDir_ == child)
        {
            this._parenteseDir_ = null;
            return;
        }

        if(this._comandoIf_ == child)
        {
            this._comandoIf_ = null;
            return;
        }

        if(this._otherwise_ == child)
        {
            this._otherwise_ = null;
            return;
        }

        if(this._comandoElse_ == child)
        {
            this._comandoElse_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._inCaseThat_ == oldChild)
        {
            setInCaseThat((TInCaseThat) newChild);
            return;
        }

        if(this._parenteseEsq_ == oldChild)
        {
            setParenteseEsq((TParenteseEsq) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._parenteseDir_ == oldChild)
        {
            setParenteseDir((TParenteseDir) newChild);
            return;
        }

        if(this._comandoIf_ == oldChild)
        {
            setComandoIf((PComando) newChild);
            return;
        }

        if(this._otherwise_ == oldChild)
        {
            setOtherwise((TOtherwise) newChild);
            return;
        }

        if(this._comandoElse_ == oldChild)
        {
            setComandoElse((PComando) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
