/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ACondicionalComandoAberto extends PComandoAberto
{
    private TInCaseThat _inCaseThat_;
    private TParenteseEsq _parenteseEsq_;
    private PExp _exp_;
    private TParenteseDir _parenteseDir_;
    private PComando _comando_;

    public ACondicionalComandoAberto()
    {
        // Constructor
    }

    public ACondicionalComandoAberto(
        @SuppressWarnings("hiding") TInCaseThat _inCaseThat_,
        @SuppressWarnings("hiding") TParenteseEsq _parenteseEsq_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TParenteseDir _parenteseDir_,
        @SuppressWarnings("hiding") PComando _comando_)
    {
        // Constructor
        setInCaseThat(_inCaseThat_);

        setParenteseEsq(_parenteseEsq_);

        setExp(_exp_);

        setParenteseDir(_parenteseDir_);

        setComando(_comando_);

    }

    @Override
    public Object clone()
    {
        return new ACondicionalComandoAberto(
            cloneNode(this._inCaseThat_),
            cloneNode(this._parenteseEsq_),
            cloneNode(this._exp_),
            cloneNode(this._parenteseDir_),
            cloneNode(this._comando_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACondicionalComandoAberto(this);
    }

    public TInCaseThat getInCaseThat()
    {
        return this._inCaseThat_;
    }

    public void setInCaseThat(TInCaseThat node)
    {
        if(this._inCaseThat_ != null)
        {
            this._inCaseThat_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inCaseThat_ = node;
    }

    public TParenteseEsq getParenteseEsq()
    {
        return this._parenteseEsq_;
    }

    public void setParenteseEsq(TParenteseEsq node)
    {
        if(this._parenteseEsq_ != null)
        {
            this._parenteseEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parenteseEsq_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TParenteseDir getParenteseDir()
    {
        return this._parenteseDir_;
    }

    public void setParenteseDir(TParenteseDir node)
    {
        if(this._parenteseDir_ != null)
        {
            this._parenteseDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parenteseDir_ = node;
    }

    public PComando getComando()
    {
        return this._comando_;
    }

    public void setComando(PComando node)
    {
        if(this._comando_ != null)
        {
            this._comando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comando_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._inCaseThat_)
            + toString(this._parenteseEsq_)
            + toString(this._exp_)
            + toString(this._parenteseDir_)
            + toString(this._comando_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._inCaseThat_ == child)
        {
            this._inCaseThat_ = null;
            return;
        }

        if(this._parenteseEsq_ == child)
        {
            this._parenteseEsq_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._parenteseDir_ == child)
        {
            this._parenteseDir_ = null;
            return;
        }

        if(this._comando_ == child)
        {
            this._comando_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._inCaseThat_ == oldChild)
        {
            setInCaseThat((TInCaseThat) newChild);
            return;
        }

        if(this._parenteseEsq_ == oldChild)
        {
            setParenteseEsq((TParenteseEsq) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._parenteseDir_ == oldChild)
        {
            setParenteseDir((TParenteseDir) newChild);
            return;
        }

        if(this._comando_ == oldChild)
        {
            setComando((PComando) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
