/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ADeclaracaoVariavelComando extends PComando
{
    private TAlterable _alterable_;
    private TNumber _number_;
    private TId _id_;
    private TAtribuicao _atribuicao_;
    private TValorInteiro _valorInteiro_;
    private TPonto _ponto_;

    public ADeclaracaoVariavelComando()
    {
        // Constructor
    }

    public ADeclaracaoVariavelComando(
        @SuppressWarnings("hiding") TAlterable _alterable_,
        @SuppressWarnings("hiding") TNumber _number_,
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TAtribuicao _atribuicao_,
        @SuppressWarnings("hiding") TValorInteiro _valorInteiro_,
        @SuppressWarnings("hiding") TPonto _ponto_)
    {
        // Constructor
        setAlterable(_alterable_);

        setNumber(_number_);

        setId(_id_);

        setAtribuicao(_atribuicao_);

        setValorInteiro(_valorInteiro_);

        setPonto(_ponto_);

    }

    @Override
    public Object clone()
    {
        return new ADeclaracaoVariavelComando(
            cloneNode(this._alterable_),
            cloneNode(this._number_),
            cloneNode(this._id_),
            cloneNode(this._atribuicao_),
            cloneNode(this._valorInteiro_),
            cloneNode(this._ponto_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclaracaoVariavelComando(this);
    }

    public TAlterable getAlterable()
    {
        return this._alterable_;
    }

    public void setAlterable(TAlterable node)
    {
        if(this._alterable_ != null)
        {
            this._alterable_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._alterable_ = node;
    }

    public TNumber getNumber()
    {
        return this._number_;
    }

    public void setNumber(TNumber node)
    {
        if(this._number_ != null)
        {
            this._number_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._number_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TAtribuicao getAtribuicao()
    {
        return this._atribuicao_;
    }

    public void setAtribuicao(TAtribuicao node)
    {
        if(this._atribuicao_ != null)
        {
            this._atribuicao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atribuicao_ = node;
    }

    public TValorInteiro getValorInteiro()
    {
        return this._valorInteiro_;
    }

    public void setValorInteiro(TValorInteiro node)
    {
        if(this._valorInteiro_ != null)
        {
            this._valorInteiro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valorInteiro_ = node;
    }

    public TPonto getPonto()
    {
        return this._ponto_;
    }

    public void setPonto(TPonto node)
    {
        if(this._ponto_ != null)
        {
            this._ponto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ponto_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._alterable_)
            + toString(this._number_)
            + toString(this._id_)
            + toString(this._atribuicao_)
            + toString(this._valorInteiro_)
            + toString(this._ponto_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._alterable_ == child)
        {
            this._alterable_ = null;
            return;
        }

        if(this._number_ == child)
        {
            this._number_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._atribuicao_ == child)
        {
            this._atribuicao_ = null;
            return;
        }

        if(this._valorInteiro_ == child)
        {
            this._valorInteiro_ = null;
            return;
        }

        if(this._ponto_ == child)
        {
            this._ponto_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._alterable_ == oldChild)
        {
            setAlterable((TAlterable) newChild);
            return;
        }

        if(this._number_ == oldChild)
        {
            setNumber((TNumber) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._atribuicao_ == oldChild)
        {
            setAtribuicao((TAtribuicao) newChild);
            return;
        }

        if(this._valorInteiro_ == oldChild)
        {
            setValorInteiro((TValorInteiro) newChild);
            return;
        }

        if(this._ponto_ == oldChild)
        {
            setPonto((TPonto) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
