/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import java.util.*;
import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ADefClasse extends PDefClasse
{
    private TIdClasse _idClasse_;
    private final LinkedList<PDeclaracao> _declaracao_ = new LinkedList<PDeclaracao>();
    private final LinkedList<PMetodo> _metodo_ = new LinkedList<PMetodo>();

    public ADefClasse()
    {
        // Constructor
    }

    public ADefClasse(
        @SuppressWarnings("hiding") TIdClasse _idClasse_,
        @SuppressWarnings("hiding") List<?> _declaracao_,
        @SuppressWarnings("hiding") List<?> _metodo_)
    {
        // Constructor
        setIdClasse(_idClasse_);

        setDeclaracao(_declaracao_);

        setMetodo(_metodo_);

    }

    @Override
    public Object clone()
    {
        return new ADefClasse(
            cloneNode(this._idClasse_),
            cloneList(this._declaracao_),
            cloneList(this._metodo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADefClasse(this);
    }

    public TIdClasse getIdClasse()
    {
        return this._idClasse_;
    }

    public void setIdClasse(TIdClasse node)
    {
        if(this._idClasse_ != null)
        {
            this._idClasse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._idClasse_ = node;
    }

    public LinkedList<PDeclaracao> getDeclaracao()
    {
        return this._declaracao_;
    }

    public void setDeclaracao(List<?> list)
    {
        for(PDeclaracao e : this._declaracao_)
        {
            e.parent(null);
        }
        this._declaracao_.clear();

        for(Object obj_e : list)
        {
            PDeclaracao e = (PDeclaracao) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._declaracao_.add(e);
        }
    }

    public LinkedList<PMetodo> getMetodo()
    {
        return this._metodo_;
    }

    public void setMetodo(List<?> list)
    {
        for(PMetodo e : this._metodo_)
        {
            e.parent(null);
        }
        this._metodo_.clear();

        for(Object obj_e : list)
        {
            PMetodo e = (PMetodo) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._metodo_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._idClasse_)
            + toString(this._declaracao_)
            + toString(this._metodo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._idClasse_ == child)
        {
            this._idClasse_ = null;
            return;
        }

        if(this._declaracao_.remove(child))
        {
            return;
        }

        if(this._metodo_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._idClasse_ == oldChild)
        {
            setIdClasse((TIdClasse) newChild);
            return;
        }

        for(ListIterator<PDeclaracao> i = this._declaracao_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDeclaracao) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator<PMetodo> i = this._metodo_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PMetodo) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
