/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AFechadoComando extends PComando
{
    private PComandoFechado _comandoFechado_;

    public AFechadoComando()
    {
        // Constructor
    }

    public AFechadoComando(
        @SuppressWarnings("hiding") PComandoFechado _comandoFechado_)
    {
        // Constructor
        setComandoFechado(_comandoFechado_);

    }

    @Override
    public Object clone()
    {
        return new AFechadoComando(
            cloneNode(this._comandoFechado_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFechadoComando(this);
    }

    public PComandoFechado getComandoFechado()
    {
        return this._comandoFechado_;
    }

    public void setComandoFechado(PComandoFechado node)
    {
        if(this._comandoFechado_ != null)
        {
            this._comandoFechado_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoFechado_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comandoFechado_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comandoFechado_ == child)
        {
            this._comandoFechado_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comandoFechado_ == oldChild)
        {
            setComandoFechado((PComandoFechado) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
