/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AHeranca extends PHeranca
{
    private TDerivesFrom _derivesFrom_;
    private TIdClasse _idClasse_;

    public AHeranca()
    {
        // Constructor
    }

    public AHeranca(
        @SuppressWarnings("hiding") TDerivesFrom _derivesFrom_,
        @SuppressWarnings("hiding") TIdClasse _idClasse_)
    {
        // Constructor
        setDerivesFrom(_derivesFrom_);

        setIdClasse(_idClasse_);

    }

    @Override
    public Object clone()
    {
        return new AHeranca(
            cloneNode(this._derivesFrom_),
            cloneNode(this._idClasse_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAHeranca(this);
    }

    public TDerivesFrom getDerivesFrom()
    {
        return this._derivesFrom_;
    }

    public void setDerivesFrom(TDerivesFrom node)
    {
        if(this._derivesFrom_ != null)
        {
            this._derivesFrom_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._derivesFrom_ = node;
    }

    public TIdClasse getIdClasse()
    {
        return this._idClasse_;
    }

    public void setIdClasse(TIdClasse node)
    {
        if(this._idClasse_ != null)
        {
            this._idClasse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._idClasse_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._derivesFrom_)
            + toString(this._idClasse_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._derivesFrom_ == child)
        {
            this._derivesFrom_ = null;
            return;
        }

        if(this._idClasse_ == child)
        {
            this._idClasse_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._derivesFrom_ == oldChild)
        {
            setDerivesFrom((TDerivesFrom) newChild);
            return;
        }

        if(this._idClasse_ == oldChild)
        {
            setIdClasse((TIdClasse) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
