/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ALacoComandoFechado extends PComandoFechado
{
    private TAsLongAs _asLongAs_;
    private TParenteseEsq _parenteseEsq_;
    private PExp _exp_;
    private TParenteseDir _parenteseDir_;
    private PComandoFechado _comandoFechado_;

    public ALacoComandoFechado()
    {
        // Constructor
    }

    public ALacoComandoFechado(
        @SuppressWarnings("hiding") TAsLongAs _asLongAs_,
        @SuppressWarnings("hiding") TParenteseEsq _parenteseEsq_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TParenteseDir _parenteseDir_,
        @SuppressWarnings("hiding") PComandoFechado _comandoFechado_)
    {
        // Constructor
        setAsLongAs(_asLongAs_);

        setParenteseEsq(_parenteseEsq_);

        setExp(_exp_);

        setParenteseDir(_parenteseDir_);

        setComandoFechado(_comandoFechado_);

    }

    @Override
    public Object clone()
    {
        return new ALacoComandoFechado(
            cloneNode(this._asLongAs_),
            cloneNode(this._parenteseEsq_),
            cloneNode(this._exp_),
            cloneNode(this._parenteseDir_),
            cloneNode(this._comandoFechado_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALacoComandoFechado(this);
    }

    public TAsLongAs getAsLongAs()
    {
        return this._asLongAs_;
    }

    public void setAsLongAs(TAsLongAs node)
    {
        if(this._asLongAs_ != null)
        {
            this._asLongAs_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._asLongAs_ = node;
    }

    public TParenteseEsq getParenteseEsq()
    {
        return this._parenteseEsq_;
    }

    public void setParenteseEsq(TParenteseEsq node)
    {
        if(this._parenteseEsq_ != null)
        {
            this._parenteseEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parenteseEsq_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TParenteseDir getParenteseDir()
    {
        return this._parenteseDir_;
    }

    public void setParenteseDir(TParenteseDir node)
    {
        if(this._parenteseDir_ != null)
        {
            this._parenteseDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parenteseDir_ = node;
    }

    public PComandoFechado getComandoFechado()
    {
        return this._comandoFechado_;
    }

    public void setComandoFechado(PComandoFechado node)
    {
        if(this._comandoFechado_ != null)
        {
            this._comandoFechado_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoFechado_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._asLongAs_)
            + toString(this._parenteseEsq_)
            + toString(this._exp_)
            + toString(this._parenteseDir_)
            + toString(this._comandoFechado_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._asLongAs_ == child)
        {
            this._asLongAs_ = null;
            return;
        }

        if(this._parenteseEsq_ == child)
        {
            this._parenteseEsq_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._parenteseDir_ == child)
        {
            this._parenteseDir_ = null;
            return;
        }

        if(this._comandoFechado_ == child)
        {
            this._comandoFechado_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._asLongAs_ == oldChild)
        {
            setAsLongAs((TAsLongAs) newChild);
            return;
        }

        if(this._parenteseEsq_ == oldChild)
        {
            setParenteseEsq((TParenteseEsq) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._parenteseDir_ == oldChild)
        {
            setParenteseDir((TParenteseDir) newChild);
            return;
        }

        if(this._comandoFechado_ == oldChild)
        {
            setComandoFechado((PComandoFechado) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
