/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import java.util.*;
import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AMetodos extends PMetodos
{
    private final LinkedList<PMetodo> _metodo_ = new LinkedList<PMetodo>();

    public AMetodos()
    {
        // Constructor
    }

    public AMetodos(
        @SuppressWarnings("hiding") List<?> _metodo_)
    {
        // Constructor
        setMetodo(_metodo_);

    }

    @Override
    public Object clone()
    {
        return new AMetodos(
            cloneList(this._metodo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMetodos(this);
    }

    public LinkedList<PMetodo> getMetodo()
    {
        return this._metodo_;
    }

    public void setMetodo(List<?> list)
    {
        for(PMetodo e : this._metodo_)
        {
            e.parent(null);
        }
        this._metodo_.clear();

        for(Object obj_e : list)
        {
            PMetodo e = (PMetodo) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._metodo_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._metodo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._metodo_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PMetodo> i = this._metodo_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PMetodo) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
