/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import java.util.*;
import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AMetodos extends PMetodos
{
    private final LinkedList<PComandoVazio> _comandoVazio_ = new LinkedList<PComandoVazio>();

    public AMetodos()
    {
        // Constructor
    }

    public AMetodos(
        @SuppressWarnings("hiding") List<?> _comandoVazio_)
    {
        // Constructor
        setComandoVazio(_comandoVazio_);

    }

    @Override
    public Object clone()
    {
        return new AMetodos(
            cloneList(this._comandoVazio_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMetodos(this);
    }

    public LinkedList<PComandoVazio> getComandoVazio()
    {
        return this._comandoVazio_;
    }

    public void setComandoVazio(List<?> list)
    {
        for(PComandoVazio e : this._comandoVazio_)
        {
            e.parent(null);
        }
        this._comandoVazio_.clear();

        for(Object obj_e : list)
        {
            PComandoVazio e = (PComandoVazio) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._comandoVazio_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comandoVazio_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comandoVazio_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PComandoVazio> i = this._comandoVazio_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PComandoVazio) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
