/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ANegacaoExpUnaria extends PExpUnaria
{
    private TNegacao _negacao_;
    private PExpUnaria _expUnaria_;

    public ANegacaoExpUnaria()
    {
        // Constructor
    }

    public ANegacaoExpUnaria(
        @SuppressWarnings("hiding") TNegacao _negacao_,
        @SuppressWarnings("hiding") PExpUnaria _expUnaria_)
    {
        // Constructor
        setNegacao(_negacao_);

        setExpUnaria(_expUnaria_);

    }

    @Override
    public Object clone()
    {
        return new ANegacaoExpUnaria(
            cloneNode(this._negacao_),
            cloneNode(this._expUnaria_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegacaoExpUnaria(this);
    }

    public TNegacao getNegacao()
    {
        return this._negacao_;
    }

    public void setNegacao(TNegacao node)
    {
        if(this._negacao_ != null)
        {
            this._negacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._negacao_ = node;
    }

    public PExpUnaria getExpUnaria()
    {
        return this._expUnaria_;
    }

    public void setExpUnaria(PExpUnaria node)
    {
        if(this._expUnaria_ != null)
        {
            this._expUnaria_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expUnaria_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._negacao_)
            + toString(this._expUnaria_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._negacao_ == child)
        {
            this._negacao_ = null;
            return;
        }

        if(this._expUnaria_ == child)
        {
            this._expUnaria_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._negacao_ == oldChild)
        {
            setNegacao((TNegacao) newChild);
            return;
        }

        if(this._expUnaria_ == oldChild)
        {
            setExpUnaria((PExpUnaria) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
