/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AOrExpOr extends PExpOr
{
    private PExpOr _expOr_;
    private TOuLogico _ouLogico_;
    private PExpAnd _expAnd_;

    public AOrExpOr()
    {
        // Constructor
    }

    public AOrExpOr(
        @SuppressWarnings("hiding") PExpOr _expOr_,
        @SuppressWarnings("hiding") TOuLogico _ouLogico_,
        @SuppressWarnings("hiding") PExpAnd _expAnd_)
    {
        // Constructor
        setExpOr(_expOr_);

        setOuLogico(_ouLogico_);

        setExpAnd(_expAnd_);

    }

    @Override
    public Object clone()
    {
        return new AOrExpOr(
            cloneNode(this._expOr_),
            cloneNode(this._ouLogico_),
            cloneNode(this._expAnd_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrExpOr(this);
    }

    public PExpOr getExpOr()
    {
        return this._expOr_;
    }

    public void setExpOr(PExpOr node)
    {
        if(this._expOr_ != null)
        {
            this._expOr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expOr_ = node;
    }

    public TOuLogico getOuLogico()
    {
        return this._ouLogico_;
    }

    public void setOuLogico(TOuLogico node)
    {
        if(this._ouLogico_ != null)
        {
            this._ouLogico_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ouLogico_ = node;
    }

    public PExpAnd getExpAnd()
    {
        return this._expAnd_;
    }

    public void setExpAnd(PExpAnd node)
    {
        if(this._expAnd_ != null)
        {
            this._expAnd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expAnd_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expOr_)
            + toString(this._ouLogico_)
            + toString(this._expAnd_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expOr_ == child)
        {
            this._expOr_ = null;
            return;
        }

        if(this._ouLogico_ == child)
        {
            this._ouLogico_ = null;
            return;
        }

        if(this._expAnd_ == child)
        {
            this._expAnd_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expOr_ == oldChild)
        {
            setExpOr((PExpOr) newChild);
            return;
        }

        if(this._ouLogico_ == oldChild)
        {
            setOuLogico((TOuLogico) newChild);
            return;
        }

        if(this._expAnd_ == oldChild)
        {
            setExpAnd((PExpAnd) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
