/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AParentesesTermo extends PTermo
{
    private TParenteseEsq _parenteseEsq_;
    private PExp _exp_;
    private TParenteseDir _parenteseDir_;

    public AParentesesTermo()
    {
        // Constructor
    }

    public AParentesesTermo(
        @SuppressWarnings("hiding") TParenteseEsq _parenteseEsq_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TParenteseDir _parenteseDir_)
    {
        // Constructor
        setParenteseEsq(_parenteseEsq_);

        setExp(_exp_);

        setParenteseDir(_parenteseDir_);

    }

    @Override
    public Object clone()
    {
        return new AParentesesTermo(
            cloneNode(this._parenteseEsq_),
            cloneNode(this._exp_),
            cloneNode(this._parenteseDir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParentesesTermo(this);
    }

    public TParenteseEsq getParenteseEsq()
    {
        return this._parenteseEsq_;
    }

    public void setParenteseEsq(TParenteseEsq node)
    {
        if(this._parenteseEsq_ != null)
        {
            this._parenteseEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parenteseEsq_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TParenteseDir getParenteseDir()
    {
        return this._parenteseDir_;
    }

    public void setParenteseDir(TParenteseDir node)
    {
        if(this._parenteseDir_ != null)
        {
            this._parenteseDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parenteseDir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parenteseEsq_)
            + toString(this._exp_)
            + toString(this._parenteseDir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parenteseEsq_ == child)
        {
            this._parenteseEsq_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._parenteseDir_ == child)
        {
            this._parenteseDir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parenteseEsq_ == oldChild)
        {
            setParenteseEsq((TParenteseEsq) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._parenteseDir_ == oldChild)
        {
            setParenteseDir((TParenteseDir) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
