/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ARelacao extends PRelacao
{
    private TIdClasse _filha_;
    private TIdClasse _mae_;

    public ARelacao()
    {
        // Constructor
    }

    public ARelacao(
        @SuppressWarnings("hiding") TIdClasse _filha_,
        @SuppressWarnings("hiding") TIdClasse _mae_)
    {
        // Constructor
        setFilha(_filha_);

        setMae(_mae_);

    }

    @Override
    public Object clone()
    {
        return new ARelacao(
            cloneNode(this._filha_),
            cloneNode(this._mae_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARelacao(this);
    }

    public TIdClasse getFilha()
    {
        return this._filha_;
    }

    public void setFilha(TIdClasse node)
    {
        if(this._filha_ != null)
        {
            this._filha_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._filha_ = node;
    }

    public TIdClasse getMae()
    {
        return this._mae_;
    }

    public void setMae(TIdClasse node)
    {
        if(this._mae_ != null)
        {
            this._mae_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mae_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._filha_)
            + toString(this._mae_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._filha_ == child)
        {
            this._filha_ = null;
            return;
        }

        if(this._mae_ == child)
        {
            this._mae_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._filha_ == oldChild)
        {
            setFilha((TIdClasse) newChild);
            return;
        }

        if(this._mae_ == oldChild)
        {
            setMae((TIdClasse) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
