/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import java.util.*;
import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ASistemaClasses extends PSistemaClasses
{
    private TFamily _family_;
    private TIdClasse _idClasse_;
    private PHeranca _heranca_;
    private TStartBlock _startBlock_;
    private final LinkedList<PComando> _comando_ = new LinkedList<PComando>();
    private TFinishBlock _finishBlock_;
    private TPonto _ponto_;

    public ASistemaClasses()
    {
        // Constructor
    }

    public ASistemaClasses(
        @SuppressWarnings("hiding") TFamily _family_,
        @SuppressWarnings("hiding") TIdClasse _idClasse_,
        @SuppressWarnings("hiding") PHeranca _heranca_,
        @SuppressWarnings("hiding") TStartBlock _startBlock_,
        @SuppressWarnings("hiding") List<?> _comando_,
        @SuppressWarnings("hiding") TFinishBlock _finishBlock_,
        @SuppressWarnings("hiding") TPonto _ponto_)
    {
        // Constructor
        setFamily(_family_);

        setIdClasse(_idClasse_);

        setHeranca(_heranca_);

        setStartBlock(_startBlock_);

        setComando(_comando_);

        setFinishBlock(_finishBlock_);

        setPonto(_ponto_);

    }

    @Override
    public Object clone()
    {
        return new ASistemaClasses(
            cloneNode(this._family_),
            cloneNode(this._idClasse_),
            cloneNode(this._heranca_),
            cloneNode(this._startBlock_),
            cloneList(this._comando_),
            cloneNode(this._finishBlock_),
            cloneNode(this._ponto_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASistemaClasses(this);
    }

    public TFamily getFamily()
    {
        return this._family_;
    }

    public void setFamily(TFamily node)
    {
        if(this._family_ != null)
        {
            this._family_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._family_ = node;
    }

    public TIdClasse getIdClasse()
    {
        return this._idClasse_;
    }

    public void setIdClasse(TIdClasse node)
    {
        if(this._idClasse_ != null)
        {
            this._idClasse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._idClasse_ = node;
    }

    public PHeranca getHeranca()
    {
        return this._heranca_;
    }

    public void setHeranca(PHeranca node)
    {
        if(this._heranca_ != null)
        {
            this._heranca_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._heranca_ = node;
    }

    public TStartBlock getStartBlock()
    {
        return this._startBlock_;
    }

    public void setStartBlock(TStartBlock node)
    {
        if(this._startBlock_ != null)
        {
            this._startBlock_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._startBlock_ = node;
    }

    public LinkedList<PComando> getComando()
    {
        return this._comando_;
    }

    public void setComando(List<?> list)
    {
        for(PComando e : this._comando_)
        {
            e.parent(null);
        }
        this._comando_.clear();

        for(Object obj_e : list)
        {
            PComando e = (PComando) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._comando_.add(e);
        }
    }

    public TFinishBlock getFinishBlock()
    {
        return this._finishBlock_;
    }

    public void setFinishBlock(TFinishBlock node)
    {
        if(this._finishBlock_ != null)
        {
            this._finishBlock_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._finishBlock_ = node;
    }

    public TPonto getPonto()
    {
        return this._ponto_;
    }

    public void setPonto(TPonto node)
    {
        if(this._ponto_ != null)
        {
            this._ponto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ponto_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._family_)
            + toString(this._idClasse_)
            + toString(this._heranca_)
            + toString(this._startBlock_)
            + toString(this._comando_)
            + toString(this._finishBlock_)
            + toString(this._ponto_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._family_ == child)
        {
            this._family_ = null;
            return;
        }

        if(this._idClasse_ == child)
        {
            this._idClasse_ = null;
            return;
        }

        if(this._heranca_ == child)
        {
            this._heranca_ = null;
            return;
        }

        if(this._startBlock_ == child)
        {
            this._startBlock_ = null;
            return;
        }

        if(this._comando_.remove(child))
        {
            return;
        }

        if(this._finishBlock_ == child)
        {
            this._finishBlock_ = null;
            return;
        }

        if(this._ponto_ == child)
        {
            this._ponto_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._family_ == oldChild)
        {
            setFamily((TFamily) newChild);
            return;
        }

        if(this._idClasse_ == oldChild)
        {
            setIdClasse((TIdClasse) newChild);
            return;
        }

        if(this._heranca_ == oldChild)
        {
            setHeranca((PHeranca) newChild);
            return;
        }

        if(this._startBlock_ == oldChild)
        {
            setStartBlock((TStartBlock) newChild);
            return;
        }

        for(ListIterator<PComando> i = this._comando_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PComando) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._finishBlock_ == oldChild)
        {
            setFinishBlock((TFinishBlock) newChild);
            return;
        }

        if(this._ponto_ == oldChild)
        {
            setPonto((TPonto) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
