/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ASubtracaoExpSoma extends PExpSoma
{
    private PExpSoma _expSoma_;
    private TSubtracao _subtracao_;
    private PExpMult _expMult_;

    public ASubtracaoExpSoma()
    {
        // Constructor
    }

    public ASubtracaoExpSoma(
        @SuppressWarnings("hiding") PExpSoma _expSoma_,
        @SuppressWarnings("hiding") TSubtracao _subtracao_,
        @SuppressWarnings("hiding") PExpMult _expMult_)
    {
        // Constructor
        setExpSoma(_expSoma_);

        setSubtracao(_subtracao_);

        setExpMult(_expMult_);

    }

    @Override
    public Object clone()
    {
        return new ASubtracaoExpSoma(
            cloneNode(this._expSoma_),
            cloneNode(this._subtracao_),
            cloneNode(this._expMult_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASubtracaoExpSoma(this);
    }

    public PExpSoma getExpSoma()
    {
        return this._expSoma_;
    }

    public void setExpSoma(PExpSoma node)
    {
        if(this._expSoma_ != null)
        {
            this._expSoma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expSoma_ = node;
    }

    public TSubtracao getSubtracao()
    {
        return this._subtracao_;
    }

    public void setSubtracao(TSubtracao node)
    {
        if(this._subtracao_ != null)
        {
            this._subtracao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._subtracao_ = node;
    }

    public PExpMult getExpMult()
    {
        return this._expMult_;
    }

    public void setExpMult(PExpMult node)
    {
        if(this._expMult_ != null)
        {
            this._expMult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expMult_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expSoma_)
            + toString(this._subtracao_)
            + toString(this._expMult_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expSoma_ == child)
        {
            this._expSoma_ = null;
            return;
        }

        if(this._subtracao_ == child)
        {
            this._subtracao_ = null;
            return;
        }

        if(this._expMult_ == child)
        {
            this._expMult_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expSoma_ == oldChild)
        {
            setExpSoma((PExpSoma) newChild);
            return;
        }

        if(this._subtracao_ == oldChild)
        {
            setSubtracao((TSubtracao) newChild);
            return;
        }

        if(this._expMult_ == oldChild)
        {
            setExpMult((PExpMult) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
