/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.analysis;

import java.util.*;
import dplusplus.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    @Override
    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    @Override
    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    @Override
    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    @Override
    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    @Override
    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPrograma(APrograma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAGenealogia(AGenealogia node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAListaRelacoes(AListaRelacoes node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARelacao(ARelacao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADefClasse(ADefClasse node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAtributos(AAtributos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAObjDeclaracao(AObjDeclaracao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVarDeclaracao(AVarDeclaracao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAConsDeclaracao(AConsDeclaracao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADecObj(ADecObj node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADecVar(ADecVar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADecCons(ADecCons node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAnswerTipoPrimitivo(AAnswerTipoPrimitivo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANumberTipoPrimitivo(ANumberTipoPrimitivo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMetodos(AMetodos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAProcedimentoMetodo(AProcedimentoMetodo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFuncaoMetodo(AFuncaoMetodo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAComComandoDecProcedimento(AComComandoDecProcedimento node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVazioDecProcedimento(AVazioDecProcedimento node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAComExpDecFuncao(AComExpDecFuncao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVaziaDecFuncao(AVaziaDecFuncao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAClasseTipo(AClasseTipo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPrimitivoTipo(APrimitivoTipo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAListaParametros(AListaParametros node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParametroExtra(AParametroExtra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParametro(AParametro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFechadoComando(AFechadoComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAbertoComando(AAbertoComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACondicionalElseComandoFechado(ACondicionalElseComandoFechado node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALacoComandoFechado(ALacoComandoFechado node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAtribuicaoComandoFechado(AAtribuicaoComandoFechado node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAtribuicaoObjComandoFechado(AAtribuicaoObjComandoFechado node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABlocoComandoFechado(ABlocoComandoFechado node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAChamadaComandoFechado(AChamadaComandoFechado node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACondicionalComandoAberto(ACondicionalComandoAberto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACondicionalElseComandoAberto(ACondicionalElseComandoAberto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALacoComandoAberto(ALacoComandoAberto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABloco(ABloco node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAListaComandos(AListaComandos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAChamada(AChamada node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAListaExp(AListaExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExpExtra(AExpExtra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAcesso(AAcesso node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABlocoExp(ABlocoExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATernarioExp(ATernarioExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAOrExp(AOrExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAOrExpOr(AOrExpOr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAndExpOr(AAndExpOr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAndExpAnd(AAndExpAnd node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIgualExpAnd(AIgualExpAnd node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIgualExpIgual(AIgualExpIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARelacionalExpIgual(ARelacionalExpIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMenorExpRelacional(AMenorExpRelacional node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMaiorExpRelacional(AMaiorExpRelacional node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASomaExpRelacional(ASomaExpRelacional node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASomaExpSoma(ASomaExpSoma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASubtracaoExpSoma(ASubtracaoExpSoma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMultExpSoma(AMultExpSoma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMultExpMult(AMultExpMult node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADivisaoExpMult(ADivisaoExpMult node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAUnariaExpMult(AUnariaExpMult node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANegacaoExpUnaria(ANegacaoExpUnaria node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANegativoExpUnaria(ANegativoExpUnaria node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATermoExpUnaria(ATermoExpUnaria node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInteiroTermo(AInteiroTermo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARealTermo(ARealTermo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAYesTermo(AYesTermo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANoTermo(ANoTermo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIdTermo(AIdTermo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAcessoTermo(AAcessoTermo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAChamadaTermo(AChamadaTermo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABlocoTermo(ABlocoTermo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParentesesTermo(AParentesesTermo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAnswer(TAnswer node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNumber(TNumber node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTYes(TYes node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNo(TNo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTStartBlock(TStartBlock node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFinishBlock(TFinishBlock node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTInCaseThat(TInCaseThat node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOtherwise(TOtherwise node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAsLongAs(TAsLongAs node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFunction(TFunction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTProcedure(TProcedure node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTObject(TObject node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAlterable(TAlterable node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTUnalterable(TUnalterable node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFamily(TFamily node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDerivesFrom(TDerivesFrom node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIf(TIf node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTElse(TElse node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSoma(TSoma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSubtracao(TSubtracao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMultiplicacao(TMultiplicacao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDivisao(TDivisao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIgual(TIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMenorQue(TMenorQue node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMaiorQue(TMaiorQue node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNegacao(TNegacao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTELogico(TELogico node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOuLogico(TOuLogico node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPonto(TPonto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPontoAcesso(TPontoAcesso node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAtribuicao(TAtribuicao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPontoEntrada(TPontoEntrada node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTColcheteEsq(TColcheteEsq node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTColcheteDir(TColcheteDir node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTParenteseEsq(TParenteseEsq node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTParenteseDir(TParenteseDir node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPipe(TPipe node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAmpersand(TAmpersand node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTValorInteiro(TValorInteiro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTValorReal(TValorReal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTId(TId node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIdClasse(TIdClasse node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComentarioLinha(TComentarioLinha node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComentarioBloco(TComentarioBloco node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEspacoVazio(TEspacoVazio node)
    {
        defaultCase(node);
    }

    @Override
    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    @Override
    public void caseInvalidToken(InvalidToken node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
