/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.analysis;

import dplusplus.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTAnswer(TAnswer node);
    void caseTNumber(TNumber node);
    void caseTYes(TYes node);
    void caseTNo(TNo node);
    void caseTStartBlock(TStartBlock node);
    void caseTFinishBlock(TFinishBlock node);
    void caseTInCaseThat(TInCaseThat node);
    void caseTOtherwise(TOtherwise node);
    void caseTAsLongAs(TAsLongAs node);
    void caseTFunction(TFunction node);
    void caseTProcedure(TProcedure node);
    void caseTObject(TObject node);
    void caseTAlterable(TAlterable node);
    void caseTUnalterable(TUnalterable node);
    void caseTFamily(TFamily node);
    void caseTDerivesFrom(TDerivesFrom node);
    void caseTIf(TIf node);
    void caseTElse(TElse node);
    void caseTSoma(TSoma node);
    void caseTSubtracao(TSubtracao node);
    void caseTMultiplicacao(TMultiplicacao node);
    void caseTDivisao(TDivisao node);
    void caseTIgual(TIgual node);
    void caseTMenorQue(TMenorQue node);
    void caseTMaiorQue(TMaiorQue node);
    void caseTNegacao(TNegacao node);
    void caseTELogico(TELogico node);
    void caseTOuLogico(TOuLogico node);
    void caseTPonto(TPonto node);
    void caseTAtribuicao(TAtribuicao node);
    void caseTPontoEntrada(TPontoEntrada node);
    void caseTColcheteEsq(TColcheteEsq node);
    void caseTColcheteDir(TColcheteDir node);
    void caseTParenteseEsq(TParenteseEsq node);
    void caseTParenteseDir(TParenteseDir node);
    void caseTPipe(TPipe node);
    void caseTAmpersand(TAmpersand node);
    void caseTValorInteiro(TValorInteiro node);
    void caseTValorReal(TValorReal node);
    void caseTId(TId node);
    void caseTIdClasse(TIdClasse node);
    void caseTComentarioLinha(TComentarioLinha node);
    void caseTComentarioBloco(TComentarioBloco node);
    void caseTEspacoVazio(TEspacoVazio node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
