/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.analysis;

import java.util.*;
import dplusplus.node.*;

public class DepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getPPrograma().apply(this);
        node.getEOF().apply(this);
        outStart(node);
    }

    public void inAPrograma(APrograma node)
    {
        defaultIn(node);
    }

    public void outAPrograma(APrograma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrograma(APrograma node)
    {
        inAPrograma(node);
        if(node.getGenealogia() != null)
        {
            node.getGenealogia().apply(this);
        }
        {
            List<PDefClasse> copy = new ArrayList<PDefClasse>(node.getDefClasse());
            for(PDefClasse e : copy)
            {
                e.apply(this);
            }
        }
        outAPrograma(node);
    }

    public void inAGenealogia(AGenealogia node)
    {
        defaultIn(node);
    }

    public void outAGenealogia(AGenealogia node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAGenealogia(AGenealogia node)
    {
        inAGenealogia(node);
        if(node.getRelacao() != null)
        {
            node.getRelacao().apply(this);
        }
        {
            List<PListaRelacoes> copy = new ArrayList<PListaRelacoes>(node.getListaRelacoes());
            for(PListaRelacoes e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        outAGenealogia(node);
    }

    public void inAListaRelacoes(AListaRelacoes node)
    {
        defaultIn(node);
    }

    public void outAListaRelacoes(AListaRelacoes node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListaRelacoes(AListaRelacoes node)
    {
        inAListaRelacoes(node);
        if(node.getAmpersand() != null)
        {
            node.getAmpersand().apply(this);
        }
        if(node.getRelacao() != null)
        {
            node.getRelacao().apply(this);
        }
        outAListaRelacoes(node);
    }

    public void inARelacao(ARelacao node)
    {
        defaultIn(node);
    }

    public void outARelacao(ARelacao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARelacao(ARelacao node)
    {
        inARelacao(node);
        if(node.getFamily() != null)
        {
            node.getFamily().apply(this);
        }
        if(node.getFilha() != null)
        {
            node.getFilha().apply(this);
        }
        if(node.getDerivesFrom() != null)
        {
            node.getDerivesFrom().apply(this);
        }
        if(node.getMae() != null)
        {
            node.getMae().apply(this);
        }
        outARelacao(node);
    }

    public void inADefClasse(ADefClasse node)
    {
        defaultIn(node);
    }

    public void outADefClasse(ADefClasse node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADefClasse(ADefClasse node)
    {
        inADefClasse(node);
        if(node.getFamily() != null)
        {
            node.getFamily().apply(this);
        }
        if(node.getIdClasse() != null)
        {
            node.getIdClasse().apply(this);
        }
        if(node.getStartBlock() != null)
        {
            node.getStartBlock().apply(this);
        }
        if(node.getAtributos() != null)
        {
            node.getAtributos().apply(this);
        }
        if(node.getMetodos() != null)
        {
            node.getMetodos().apply(this);
        }
        if(node.getFinishBlock() != null)
        {
            node.getFinishBlock().apply(this);
        }
        outADefClasse(node);
    }

    public void inAAtributos(AAtributos node)
    {
        defaultIn(node);
    }

    public void outAAtributos(AAtributos node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAtributos(AAtributos node)
    {
        inAAtributos(node);
        {
            List<PDeclaracao> copy = new ArrayList<PDeclaracao>(node.getDeclaracao());
            for(PDeclaracao e : copy)
            {
                e.apply(this);
            }
        }
        outAAtributos(node);
    }

    public void inAObjDeclaracao(AObjDeclaracao node)
    {
        defaultIn(node);
    }

    public void outAObjDeclaracao(AObjDeclaracao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAObjDeclaracao(AObjDeclaracao node)
    {
        inAObjDeclaracao(node);
        if(node.getDecObj() != null)
        {
            node.getDecObj().apply(this);
        }
        outAObjDeclaracao(node);
    }

    public void inAVarDeclaracao(AVarDeclaracao node)
    {
        defaultIn(node);
    }

    public void outAVarDeclaracao(AVarDeclaracao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVarDeclaracao(AVarDeclaracao node)
    {
        inAVarDeclaracao(node);
        if(node.getDecVar() != null)
        {
            node.getDecVar().apply(this);
        }
        outAVarDeclaracao(node);
    }

    public void inAConsDeclaracao(AConsDeclaracao node)
    {
        defaultIn(node);
    }

    public void outAConsDeclaracao(AConsDeclaracao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAConsDeclaracao(AConsDeclaracao node)
    {
        inAConsDeclaracao(node);
        if(node.getDecCons() != null)
        {
            node.getDecCons().apply(this);
        }
        outAConsDeclaracao(node);
    }

    public void inADecObj(ADecObj node)
    {
        defaultIn(node);
    }

    public void outADecObj(ADecObj node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecObj(ADecObj node)
    {
        inADecObj(node);
        if(node.getObject() != null)
        {
            node.getObject().apply(this);
        }
        if(node.getIdClasse() != null)
        {
            node.getIdClasse().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        outADecObj(node);
    }

    public void inADecVar(ADecVar node)
    {
        defaultIn(node);
    }

    public void outADecVar(ADecVar node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecVar(ADecVar node)
    {
        inADecVar(node);
        if(node.getAlterable() != null)
        {
            node.getAlterable().apply(this);
        }
        if(node.getTipoPrimitivo() != null)
        {
            node.getTipoPrimitivo().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getAtribuicao() != null)
        {
            node.getAtribuicao().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        outADecVar(node);
    }

    public void inADecCons(ADecCons node)
    {
        defaultIn(node);
    }

    public void outADecCons(ADecCons node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecCons(ADecCons node)
    {
        inADecCons(node);
        if(node.getUnalterable() != null)
        {
            node.getUnalterable().apply(this);
        }
        if(node.getTipoPrimitivo() != null)
        {
            node.getTipoPrimitivo().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getAtribuicao() != null)
        {
            node.getAtribuicao().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        outADecCons(node);
    }

    public void inAAnswerTipoPrimitivo(AAnswerTipoPrimitivo node)
    {
        defaultIn(node);
    }

    public void outAAnswerTipoPrimitivo(AAnswerTipoPrimitivo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAnswerTipoPrimitivo(AAnswerTipoPrimitivo node)
    {
        inAAnswerTipoPrimitivo(node);
        if(node.getAnswer() != null)
        {
            node.getAnswer().apply(this);
        }
        outAAnswerTipoPrimitivo(node);
    }

    public void inANumberTipoPrimitivo(ANumberTipoPrimitivo node)
    {
        defaultIn(node);
    }

    public void outANumberTipoPrimitivo(ANumberTipoPrimitivo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANumberTipoPrimitivo(ANumberTipoPrimitivo node)
    {
        inANumberTipoPrimitivo(node);
        if(node.getNumber() != null)
        {
            node.getNumber().apply(this);
        }
        outANumberTipoPrimitivo(node);
    }

    public void inAMetodos(AMetodos node)
    {
        defaultIn(node);
    }

    public void outAMetodos(AMetodos node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMetodos(AMetodos node)
    {
        inAMetodos(node);
        {
            List<PComandoVazio> copy = new ArrayList<PComandoVazio>(node.getComandoVazio());
            for(PComandoVazio e : copy)
            {
                e.apply(this);
            }
        }
        outAMetodos(node);
    }

    public void inAComandoVazio(AComandoVazio node)
    {
        defaultIn(node);
    }

    public void outAComandoVazio(AComandoVazio node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAComandoVazio(AComandoVazio node)
    {
        inAComandoVazio(node);
        if(node.getStartBlock() != null)
        {
            node.getStartBlock().apply(this);
        }
        if(node.getFinishBlock() != null)
        {
            node.getFinishBlock().apply(this);
        }
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        outAComandoVazio(node);
    }

    public void inAInteiroExp(AInteiroExp node)
    {
        defaultIn(node);
    }

    public void outAInteiroExp(AInteiroExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAInteiroExp(AInteiroExp node)
    {
        inAInteiroExp(node);
        if(node.getValorInteiro() != null)
        {
            node.getValorInteiro().apply(this);
        }
        outAInteiroExp(node);
    }
}
