/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.analysis;

import java.util.*;
import dplusplus.node.*;

public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPPrograma().apply(this);
        outStart(node);
    }

    public void inAPrograma(APrograma node)
    {
        defaultIn(node);
    }

    public void outAPrograma(APrograma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrograma(APrograma node)
    {
        inAPrograma(node);
        {
            List<PDefClasse> copy = new ArrayList<PDefClasse>(node.getDefClasse());
            Collections.reverse(copy);
            for(PDefClasse e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getGenealogia() != null)
        {
            node.getGenealogia().apply(this);
        }
        outAPrograma(node);
    }

    public void inAGenealogia(AGenealogia node)
    {
        defaultIn(node);
    }

    public void outAGenealogia(AGenealogia node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAGenealogia(AGenealogia node)
    {
        inAGenealogia(node);
        {
            List<PRelacao> copy = new ArrayList<PRelacao>(node.getRelacao());
            Collections.reverse(copy);
            for(PRelacao e : copy)
            {
                e.apply(this);
            }
        }
        outAGenealogia(node);
    }

    public void inARelacao(ARelacao node)
    {
        defaultIn(node);
    }

    public void outARelacao(ARelacao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARelacao(ARelacao node)
    {
        inARelacao(node);
        if(node.getMae() != null)
        {
            node.getMae().apply(this);
        }
        if(node.getFilha() != null)
        {
            node.getFilha().apply(this);
        }
        outARelacao(node);
    }

    public void inADefClasse(ADefClasse node)
    {
        defaultIn(node);
    }

    public void outADefClasse(ADefClasse node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADefClasse(ADefClasse node)
    {
        inADefClasse(node);
        {
            List<PMetodo> copy = new ArrayList<PMetodo>(node.getMetodo());
            Collections.reverse(copy);
            for(PMetodo e : copy)
            {
                e.apply(this);
            }
        }
        {
            List<PDeclaracao> copy = new ArrayList<PDeclaracao>(node.getDeclaracao());
            Collections.reverse(copy);
            for(PDeclaracao e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getIdClasse() != null)
        {
            node.getIdClasse().apply(this);
        }
        outADefClasse(node);
    }

    public void inAObjDeclaracao(AObjDeclaracao node)
    {
        defaultIn(node);
    }

    public void outAObjDeclaracao(AObjDeclaracao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAObjDeclaracao(AObjDeclaracao node)
    {
        inAObjDeclaracao(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getIdClasse() != null)
        {
            node.getIdClasse().apply(this);
        }
        outAObjDeclaracao(node);
    }

    public void inAVarDeclaracao(AVarDeclaracao node)
    {
        defaultIn(node);
    }

    public void outAVarDeclaracao(AVarDeclaracao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVarDeclaracao(AVarDeclaracao node)
    {
        inAVarDeclaracao(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getTipoPrimitivo() != null)
        {
            node.getTipoPrimitivo().apply(this);
        }
        outAVarDeclaracao(node);
    }

    public void inAConsDeclaracao(AConsDeclaracao node)
    {
        defaultIn(node);
    }

    public void outAConsDeclaracao(AConsDeclaracao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAConsDeclaracao(AConsDeclaracao node)
    {
        inAConsDeclaracao(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getTipoPrimitivo() != null)
        {
            node.getTipoPrimitivo().apply(this);
        }
        outAConsDeclaracao(node);
    }

    public void inAAnswerTipoPrimitivo(AAnswerTipoPrimitivo node)
    {
        defaultIn(node);
    }

    public void outAAnswerTipoPrimitivo(AAnswerTipoPrimitivo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAnswerTipoPrimitivo(AAnswerTipoPrimitivo node)
    {
        inAAnswerTipoPrimitivo(node);
        outAAnswerTipoPrimitivo(node);
    }

    public void inANumberTipoPrimitivo(ANumberTipoPrimitivo node)
    {
        defaultIn(node);
    }

    public void outANumberTipoPrimitivo(ANumberTipoPrimitivo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANumberTipoPrimitivo(ANumberTipoPrimitivo node)
    {
        inANumberTipoPrimitivo(node);
        outANumberTipoPrimitivo(node);
    }

    public void inAProcedimentoCmdMetodo(AProcedimentoCmdMetodo node)
    {
        defaultIn(node);
    }

    public void outAProcedimentoCmdMetodo(AProcedimentoCmdMetodo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAProcedimentoCmdMetodo(AProcedimentoCmdMetodo node)
    {
        inAProcedimentoCmdMetodo(node);
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        {
            List<PParametro> copy = new ArrayList<PParametro>(node.getParametro());
            Collections.reverse(copy);
            for(PParametro e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getPontoEntrada() != null)
        {
            node.getPontoEntrada().apply(this);
        }
        outAProcedimentoCmdMetodo(node);
    }

    public void inAProcedimentoVazioMetodo(AProcedimentoVazioMetodo node)
    {
        defaultIn(node);
    }

    public void outAProcedimentoVazioMetodo(AProcedimentoVazioMetodo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAProcedimentoVazioMetodo(AProcedimentoVazioMetodo node)
    {
        inAProcedimentoVazioMetodo(node);
        {
            List<PParametro> copy = new ArrayList<PParametro>(node.getParametro());
            Collections.reverse(copy);
            for(PParametro e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getPontoEntrada() != null)
        {
            node.getPontoEntrada().apply(this);
        }
        outAProcedimentoVazioMetodo(node);
    }

    public void inAFuncaoExpMetodo(AFuncaoExpMetodo node)
    {
        defaultIn(node);
    }

    public void outAFuncaoExpMetodo(AFuncaoExpMetodo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFuncaoExpMetodo(AFuncaoExpMetodo node)
    {
        inAFuncaoExpMetodo(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        {
            List<PParametro> copy = new ArrayList<PParametro>(node.getParametro());
            Collections.reverse(copy);
            for(PParametro e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        outAFuncaoExpMetodo(node);
    }

    public void inAFuncaoVaziaMetodo(AFuncaoVaziaMetodo node)
    {
        defaultIn(node);
    }

    public void outAFuncaoVaziaMetodo(AFuncaoVaziaMetodo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFuncaoVaziaMetodo(AFuncaoVaziaMetodo node)
    {
        inAFuncaoVaziaMetodo(node);
        {
            List<PParametro> copy = new ArrayList<PParametro>(node.getParametro());
            Collections.reverse(copy);
            for(PParametro e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        outAFuncaoVaziaMetodo(node);
    }

    public void inAClasseTipo(AClasseTipo node)
    {
        defaultIn(node);
    }

    public void outAClasseTipo(AClasseTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAClasseTipo(AClasseTipo node)
    {
        inAClasseTipo(node);
        if(node.getIdClasse() != null)
        {
            node.getIdClasse().apply(this);
        }
        outAClasseTipo(node);
    }

    public void inAPrimitivoTipo(APrimitivoTipo node)
    {
        defaultIn(node);
    }

    public void outAPrimitivoTipo(APrimitivoTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrimitivoTipo(APrimitivoTipo node)
    {
        inAPrimitivoTipo(node);
        if(node.getTipoPrimitivo() != null)
        {
            node.getTipoPrimitivo().apply(this);
        }
        outAPrimitivoTipo(node);
    }

    public void inAParametro(AParametro node)
    {
        defaultIn(node);
    }

    public void outAParametro(AParametro node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParametro(AParametro node)
    {
        inAParametro(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        outAParametro(node);
    }

    public void inACondicionalComando(ACondicionalComando node)
    {
        defaultIn(node);
    }

    public void outACondicionalComando(ACondicionalComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACondicionalComando(ACondicionalComando node)
    {
        inACondicionalComando(node);
        if(node.getComandoElse() != null)
        {
            node.getComandoElse().apply(this);
        }
        if(node.getComandoIf() != null)
        {
            node.getComandoIf().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outACondicionalComando(node);
    }

    public void inALacoComando(ALacoComando node)
    {
        defaultIn(node);
    }

    public void outALacoComando(ALacoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALacoComando(ALacoComando node)
    {
        inALacoComando(node);
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outALacoComando(node);
    }

    public void inAAtribuicaoComando(AAtribuicaoComando node)
    {
        defaultIn(node);
    }

    public void outAAtribuicaoComando(AAtribuicaoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAtribuicaoComando(AAtribuicaoComando node)
    {
        inAAtribuicaoComando(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAAtribuicaoComando(node);
    }

    public void inAAtribuicaoObjComando(AAtribuicaoObjComando node)
    {
        defaultIn(node);
    }

    public void outAAtribuicaoObjComando(AAtribuicaoObjComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAtribuicaoObjComando(AAtribuicaoObjComando node)
    {
        inAAtribuicaoObjComando(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getAcesso() != null)
        {
            node.getAcesso().apply(this);
        }
        outAAtribuicaoObjComando(node);
    }

    public void inABlocoComando(ABlocoComando node)
    {
        defaultIn(node);
    }

    public void outABlocoComando(ABlocoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlocoComando(ABlocoComando node)
    {
        inABlocoComando(node);
        if(node.getBloco() != null)
        {
            node.getBloco().apply(this);
        }
        outABlocoComando(node);
    }

    public void inAChamadaComando(AChamadaComando node)
    {
        defaultIn(node);
    }

    public void outAChamadaComando(AChamadaComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAChamadaComando(AChamadaComando node)
    {
        inAChamadaComando(node);
        if(node.getChamada() != null)
        {
            node.getChamada().apply(this);
        }
        outAChamadaComando(node);
    }

    public void inABloco(ABloco node)
    {
        defaultIn(node);
    }

    public void outABloco(ABloco node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABloco(ABloco node)
    {
        inABloco(node);
        {
            List<PComando> copy = new ArrayList<PComando>(node.getComando());
            Collections.reverse(copy);
            for(PComando e : copy)
            {
                e.apply(this);
            }
        }
        {
            List<PDeclaracao> copy = new ArrayList<PDeclaracao>(node.getDeclaracao());
            Collections.reverse(copy);
            for(PDeclaracao e : copy)
            {
                e.apply(this);
            }
        }
        outABloco(node);
    }

    public void inAChamada(AChamada node)
    {
        defaultIn(node);
    }

    public void outAChamada(AChamada node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAChamada(AChamada node)
    {
        inAChamada(node);
        {
            List<PExp> copy = new ArrayList<PExp>(node.getArgumentos());
            Collections.reverse(copy);
            for(PExp e : copy)
            {
                e.apply(this);
            }
        }
        {
            List<TId> copy = new ArrayList<TId>(node.getAcessos());
            Collections.reverse(copy);
            for(TId e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getBase() != null)
        {
            node.getBase().apply(this);
        }
        outAChamada(node);
    }

    public void inAAcesso(AAcesso node)
    {
        defaultIn(node);
    }

    public void outAAcesso(AAcesso node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAcesso(AAcesso node)
    {
        inAAcesso(node);
        {
            List<TId> copy = new ArrayList<TId>(node.getAcessos());
            Collections.reverse(copy);
            for(TId e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getBase() != null)
        {
            node.getBase().apply(this);
        }
        outAAcesso(node);
    }

    public void inABlocoExp(ABlocoExp node)
    {
        defaultIn(node);
    }

    public void outABlocoExp(ABlocoExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlocoExp(ABlocoExp node)
    {
        inABlocoExp(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        {
            List<PDeclaracao> copy = new ArrayList<PDeclaracao>(node.getDeclaracao());
            Collections.reverse(copy);
            for(PDeclaracao e : copy)
            {
                e.apply(this);
            }
        }
        outABlocoExp(node);
    }

    public void inATernarioExp(ATernarioExp node)
    {
        defaultIn(node);
    }

    public void outATernarioExp(ATernarioExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATernarioExp(ATernarioExp node)
    {
        inATernarioExp(node);
        if(node.getExpElse() != null)
        {
            node.getExpElse().apply(this);
        }
        if(node.getExpIf() != null)
        {
            node.getExpIf().apply(this);
        }
        if(node.getCondicao() != null)
        {
            node.getCondicao().apply(this);
        }
        outATernarioExp(node);
    }

    public void inAOrExp(AOrExp node)
    {
        defaultIn(node);
    }

    public void outAOrExp(AOrExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOrExp(AOrExp node)
    {
        inAOrExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outAOrExp(node);
    }

    public void inAAndExp(AAndExp node)
    {
        defaultIn(node);
    }

    public void outAAndExp(AAndExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAndExp(AAndExp node)
    {
        inAAndExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outAAndExp(node);
    }

    public void inAIgualExp(AIgualExp node)
    {
        defaultIn(node);
    }

    public void outAIgualExp(AIgualExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIgualExp(AIgualExp node)
    {
        inAIgualExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outAIgualExp(node);
    }

    public void inAMenorExp(AMenorExp node)
    {
        defaultIn(node);
    }

    public void outAMenorExp(AMenorExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenorExp(AMenorExp node)
    {
        inAMenorExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outAMenorExp(node);
    }

    public void inAMaiorExp(AMaiorExp node)
    {
        defaultIn(node);
    }

    public void outAMaiorExp(AMaiorExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMaiorExp(AMaiorExp node)
    {
        inAMaiorExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outAMaiorExp(node);
    }

    public void inASomaExp(ASomaExp node)
    {
        defaultIn(node);
    }

    public void outASomaExp(ASomaExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASomaExp(ASomaExp node)
    {
        inASomaExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outASomaExp(node);
    }

    public void inASubtracaoExp(ASubtracaoExp node)
    {
        defaultIn(node);
    }

    public void outASubtracaoExp(ASubtracaoExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASubtracaoExp(ASubtracaoExp node)
    {
        inASubtracaoExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outASubtracaoExp(node);
    }

    public void inAMultExp(AMultExp node)
    {
        defaultIn(node);
    }

    public void outAMultExp(AMultExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultExp(AMultExp node)
    {
        inAMultExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outAMultExp(node);
    }

    public void inADivisaoExp(ADivisaoExp node)
    {
        defaultIn(node);
    }

    public void outADivisaoExp(ADivisaoExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADivisaoExp(ADivisaoExp node)
    {
        inADivisaoExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outADivisaoExp(node);
    }

    public void inANegacaoExp(ANegacaoExp node)
    {
        defaultIn(node);
    }

    public void outANegacaoExp(ANegacaoExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANegacaoExp(ANegacaoExp node)
    {
        inANegacaoExp(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outANegacaoExp(node);
    }

    public void inANegativoExp(ANegativoExp node)
    {
        defaultIn(node);
    }

    public void outANegativoExp(ANegativoExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANegativoExp(ANegativoExp node)
    {
        inANegativoExp(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outANegativoExp(node);
    }

    public void inAInteiroExp(AInteiroExp node)
    {
        defaultIn(node);
    }

    public void outAInteiroExp(AInteiroExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAInteiroExp(AInteiroExp node)
    {
        inAInteiroExp(node);
        if(node.getValorInteiro() != null)
        {
            node.getValorInteiro().apply(this);
        }
        outAInteiroExp(node);
    }

    public void inARealExp(ARealExp node)
    {
        defaultIn(node);
    }

    public void outARealExp(ARealExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARealExp(ARealExp node)
    {
        inARealExp(node);
        if(node.getValorReal() != null)
        {
            node.getValorReal().apply(this);
        }
        outARealExp(node);
    }

    public void inAYesExp(AYesExp node)
    {
        defaultIn(node);
    }

    public void outAYesExp(AYesExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAYesExp(AYesExp node)
    {
        inAYesExp(node);
        outAYesExp(node);
    }

    public void inANoExp(ANoExp node)
    {
        defaultIn(node);
    }

    public void outANoExp(ANoExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANoExp(ANoExp node)
    {
        inANoExp(node);
        outANoExp(node);
    }

    public void inAIdExp(AIdExp node)
    {
        defaultIn(node);
    }

    public void outAIdExp(AIdExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdExp(AIdExp node)
    {
        inAIdExp(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAIdExp(node);
    }

    public void inAAcessoExp(AAcessoExp node)
    {
        defaultIn(node);
    }

    public void outAAcessoExp(AAcessoExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAcessoExp(AAcessoExp node)
    {
        inAAcessoExp(node);
        if(node.getAcesso() != null)
        {
            node.getAcesso().apply(this);
        }
        outAAcessoExp(node);
    }

    public void inAChamadaExp(AChamadaExp node)
    {
        defaultIn(node);
    }

    public void outAChamadaExp(AChamadaExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAChamadaExp(AChamadaExp node)
    {
        inAChamadaExp(node);
        if(node.getChamada() != null)
        {
            node.getChamada().apply(this);
        }
        outAChamadaExp(node);
    }

    public void inABlocoRetornoExp(ABlocoRetornoExp node)
    {
        defaultIn(node);
    }

    public void outABlocoRetornoExp(ABlocoRetornoExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlocoRetornoExp(ABlocoRetornoExp node)
    {
        inABlocoRetornoExp(node);
        if(node.getBlocoExp() != null)
        {
            node.getBlocoExp().apply(this);
        }
        outABlocoRetornoExp(node);
    }
}
