/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.analysis;

import java.util.*;
import dplusplus.node.*;

public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPPrograma().apply(this);
        outStart(node);
    }

    public void inAPrograma(APrograma node)
    {
        defaultIn(node);
    }

    public void outAPrograma(APrograma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrograma(APrograma node)
    {
        inAPrograma(node);
        {
            List<PDefClasse> copy = new ArrayList<PDefClasse>(node.getDefClasse());
            Collections.reverse(copy);
            for(PDefClasse e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getGenealogia() != null)
        {
            node.getGenealogia().apply(this);
        }
        outAPrograma(node);
    }

    public void inAGenealogia(AGenealogia node)
    {
        defaultIn(node);
    }

    public void outAGenealogia(AGenealogia node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAGenealogia(AGenealogia node)
    {
        inAGenealogia(node);
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        {
            List<PListaRelacoes> copy = new ArrayList<PListaRelacoes>(node.getListaRelacoes());
            Collections.reverse(copy);
            for(PListaRelacoes e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getRelacao() != null)
        {
            node.getRelacao().apply(this);
        }
        outAGenealogia(node);
    }

    public void inAListaRelacoes(AListaRelacoes node)
    {
        defaultIn(node);
    }

    public void outAListaRelacoes(AListaRelacoes node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListaRelacoes(AListaRelacoes node)
    {
        inAListaRelacoes(node);
        if(node.getRelacao() != null)
        {
            node.getRelacao().apply(this);
        }
        if(node.getAmpersand() != null)
        {
            node.getAmpersand().apply(this);
        }
        outAListaRelacoes(node);
    }

    public void inARelacao(ARelacao node)
    {
        defaultIn(node);
    }

    public void outARelacao(ARelacao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARelacao(ARelacao node)
    {
        inARelacao(node);
        if(node.getMae() != null)
        {
            node.getMae().apply(this);
        }
        if(node.getDerivesFrom() != null)
        {
            node.getDerivesFrom().apply(this);
        }
        if(node.getFilha() != null)
        {
            node.getFilha().apply(this);
        }
        if(node.getFamily() != null)
        {
            node.getFamily().apply(this);
        }
        outARelacao(node);
    }

    public void inADefClasse(ADefClasse node)
    {
        defaultIn(node);
    }

    public void outADefClasse(ADefClasse node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADefClasse(ADefClasse node)
    {
        inADefClasse(node);
        if(node.getFinishBlock() != null)
        {
            node.getFinishBlock().apply(this);
        }
        if(node.getMetodos() != null)
        {
            node.getMetodos().apply(this);
        }
        if(node.getAtributos() != null)
        {
            node.getAtributos().apply(this);
        }
        if(node.getStartBlock() != null)
        {
            node.getStartBlock().apply(this);
        }
        if(node.getIdClasse() != null)
        {
            node.getIdClasse().apply(this);
        }
        if(node.getFamily() != null)
        {
            node.getFamily().apply(this);
        }
        outADefClasse(node);
    }

    public void inAAtributos(AAtributos node)
    {
        defaultIn(node);
    }

    public void outAAtributos(AAtributos node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAtributos(AAtributos node)
    {
        inAAtributos(node);
        {
            List<PDeclaracao> copy = new ArrayList<PDeclaracao>(node.getDeclaracao());
            Collections.reverse(copy);
            for(PDeclaracao e : copy)
            {
                e.apply(this);
            }
        }
        outAAtributos(node);
    }

    public void inAObjDeclaracao(AObjDeclaracao node)
    {
        defaultIn(node);
    }

    public void outAObjDeclaracao(AObjDeclaracao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAObjDeclaracao(AObjDeclaracao node)
    {
        inAObjDeclaracao(node);
        if(node.getDecObj() != null)
        {
            node.getDecObj().apply(this);
        }
        outAObjDeclaracao(node);
    }

    public void inAVarDeclaracao(AVarDeclaracao node)
    {
        defaultIn(node);
    }

    public void outAVarDeclaracao(AVarDeclaracao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVarDeclaracao(AVarDeclaracao node)
    {
        inAVarDeclaracao(node);
        if(node.getDecVar() != null)
        {
            node.getDecVar().apply(this);
        }
        outAVarDeclaracao(node);
    }

    public void inAConsDeclaracao(AConsDeclaracao node)
    {
        defaultIn(node);
    }

    public void outAConsDeclaracao(AConsDeclaracao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAConsDeclaracao(AConsDeclaracao node)
    {
        inAConsDeclaracao(node);
        if(node.getDecCons() != null)
        {
            node.getDecCons().apply(this);
        }
        outAConsDeclaracao(node);
    }

    public void inADecObj(ADecObj node)
    {
        defaultIn(node);
    }

    public void outADecObj(ADecObj node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecObj(ADecObj node)
    {
        inADecObj(node);
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getIdClasse() != null)
        {
            node.getIdClasse().apply(this);
        }
        if(node.getObject() != null)
        {
            node.getObject().apply(this);
        }
        outADecObj(node);
    }

    public void inADecVar(ADecVar node)
    {
        defaultIn(node);
    }

    public void outADecVar(ADecVar node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecVar(ADecVar node)
    {
        inADecVar(node);
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getAtribuicao() != null)
        {
            node.getAtribuicao().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getTipoPrimitivo() != null)
        {
            node.getTipoPrimitivo().apply(this);
        }
        if(node.getAlterable() != null)
        {
            node.getAlterable().apply(this);
        }
        outADecVar(node);
    }

    public void inADecCons(ADecCons node)
    {
        defaultIn(node);
    }

    public void outADecCons(ADecCons node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecCons(ADecCons node)
    {
        inADecCons(node);
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getAtribuicao() != null)
        {
            node.getAtribuicao().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getTipoPrimitivo() != null)
        {
            node.getTipoPrimitivo().apply(this);
        }
        if(node.getUnalterable() != null)
        {
            node.getUnalterable().apply(this);
        }
        outADecCons(node);
    }

    public void inAAnswerTipoPrimitivo(AAnswerTipoPrimitivo node)
    {
        defaultIn(node);
    }

    public void outAAnswerTipoPrimitivo(AAnswerTipoPrimitivo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAnswerTipoPrimitivo(AAnswerTipoPrimitivo node)
    {
        inAAnswerTipoPrimitivo(node);
        if(node.getAnswer() != null)
        {
            node.getAnswer().apply(this);
        }
        outAAnswerTipoPrimitivo(node);
    }

    public void inANumberTipoPrimitivo(ANumberTipoPrimitivo node)
    {
        defaultIn(node);
    }

    public void outANumberTipoPrimitivo(ANumberTipoPrimitivo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANumberTipoPrimitivo(ANumberTipoPrimitivo node)
    {
        inANumberTipoPrimitivo(node);
        if(node.getNumber() != null)
        {
            node.getNumber().apply(this);
        }
        outANumberTipoPrimitivo(node);
    }

    public void inAMetodos(AMetodos node)
    {
        defaultIn(node);
    }

    public void outAMetodos(AMetodos node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMetodos(AMetodos node)
    {
        inAMetodos(node);
        {
            List<PMetodo> copy = new ArrayList<PMetodo>(node.getMetodo());
            Collections.reverse(copy);
            for(PMetodo e : copy)
            {
                e.apply(this);
            }
        }
        outAMetodos(node);
    }

    public void inAProcedimentoMetodo(AProcedimentoMetodo node)
    {
        defaultIn(node);
    }

    public void outAProcedimentoMetodo(AProcedimentoMetodo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAProcedimentoMetodo(AProcedimentoMetodo node)
    {
        inAProcedimentoMetodo(node);
        if(node.getDecProcedimento() != null)
        {
            node.getDecProcedimento().apply(this);
        }
        outAProcedimentoMetodo(node);
    }

    public void inAFuncaoMetodo(AFuncaoMetodo node)
    {
        defaultIn(node);
    }

    public void outAFuncaoMetodo(AFuncaoMetodo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFuncaoMetodo(AFuncaoMetodo node)
    {
        inAFuncaoMetodo(node);
        if(node.getDecFuncao() != null)
        {
            node.getDecFuncao().apply(this);
        }
        outAFuncaoMetodo(node);
    }

    public void inAComComandoDecProcedimento(AComComandoDecProcedimento node)
    {
        defaultIn(node);
    }

    public void outAComComandoDecProcedimento(AComComandoDecProcedimento node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAComComandoDecProcedimento(AComComandoDecProcedimento node)
    {
        inAComComandoDecProcedimento(node);
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        if(node.getColcheteDir() != null)
        {
            node.getColcheteDir().apply(this);
        }
        if(node.getListaParametros() != null)
        {
            node.getListaParametros().apply(this);
        }
        if(node.getColcheteEsq() != null)
        {
            node.getColcheteEsq().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getProcedure() != null)
        {
            node.getProcedure().apply(this);
        }
        if(node.getPontoEntrada() != null)
        {
            node.getPontoEntrada().apply(this);
        }
        outAComComandoDecProcedimento(node);
    }

    public void inAVazioDecProcedimento(AVazioDecProcedimento node)
    {
        defaultIn(node);
    }

    public void outAVazioDecProcedimento(AVazioDecProcedimento node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVazioDecProcedimento(AVazioDecProcedimento node)
    {
        inAVazioDecProcedimento(node);
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        if(node.getColcheteDir() != null)
        {
            node.getColcheteDir().apply(this);
        }
        if(node.getListaParametros() != null)
        {
            node.getListaParametros().apply(this);
        }
        if(node.getColcheteEsq() != null)
        {
            node.getColcheteEsq().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getProcedure() != null)
        {
            node.getProcedure().apply(this);
        }
        if(node.getPontoEntrada() != null)
        {
            node.getPontoEntrada().apply(this);
        }
        outAVazioDecProcedimento(node);
    }

    public void inAComExpDecFuncao(AComExpDecFuncao node)
    {
        defaultIn(node);
    }

    public void outAComExpDecFuncao(AComExpDecFuncao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAComExpDecFuncao(AComExpDecFuncao node)
    {
        inAComExpDecFuncao(node);
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getColcheteDir() != null)
        {
            node.getColcheteDir().apply(this);
        }
        if(node.getListaParametros() != null)
        {
            node.getListaParametros().apply(this);
        }
        if(node.getColcheteEsq() != null)
        {
            node.getColcheteEsq().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        if(node.getFunction() != null)
        {
            node.getFunction().apply(this);
        }
        outAComExpDecFuncao(node);
    }

    public void inAVaziaDecFuncao(AVaziaDecFuncao node)
    {
        defaultIn(node);
    }

    public void outAVaziaDecFuncao(AVaziaDecFuncao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVaziaDecFuncao(AVaziaDecFuncao node)
    {
        inAVaziaDecFuncao(node);
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        if(node.getColcheteDir() != null)
        {
            node.getColcheteDir().apply(this);
        }
        if(node.getListaParametros() != null)
        {
            node.getListaParametros().apply(this);
        }
        if(node.getColcheteEsq() != null)
        {
            node.getColcheteEsq().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        if(node.getFunction() != null)
        {
            node.getFunction().apply(this);
        }
        outAVaziaDecFuncao(node);
    }

    public void inAClasseTipo(AClasseTipo node)
    {
        defaultIn(node);
    }

    public void outAClasseTipo(AClasseTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAClasseTipo(AClasseTipo node)
    {
        inAClasseTipo(node);
        if(node.getIdClasse() != null)
        {
            node.getIdClasse().apply(this);
        }
        outAClasseTipo(node);
    }

    public void inAPrimitivoTipo(APrimitivoTipo node)
    {
        defaultIn(node);
    }

    public void outAPrimitivoTipo(APrimitivoTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrimitivoTipo(APrimitivoTipo node)
    {
        inAPrimitivoTipo(node);
        if(node.getTipoPrimitivo() != null)
        {
            node.getTipoPrimitivo().apply(this);
        }
        outAPrimitivoTipo(node);
    }

    public void inAListaParametros(AListaParametros node)
    {
        defaultIn(node);
    }

    public void outAListaParametros(AListaParametros node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListaParametros(AListaParametros node)
    {
        inAListaParametros(node);
        {
            List<PParametroExtra> copy = new ArrayList<PParametroExtra>(node.getParametroExtra());
            Collections.reverse(copy);
            for(PParametroExtra e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getParametro() != null)
        {
            node.getParametro().apply(this);
        }
        outAListaParametros(node);
    }

    public void inAParametroExtra(AParametroExtra node)
    {
        defaultIn(node);
    }

    public void outAParametroExtra(AParametroExtra node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParametroExtra(AParametroExtra node)
    {
        inAParametroExtra(node);
        if(node.getParametro() != null)
        {
            node.getParametro().apply(this);
        }
        if(node.getPipe() != null)
        {
            node.getPipe().apply(this);
        }
        outAParametroExtra(node);
    }

    public void inAParametro(AParametro node)
    {
        defaultIn(node);
    }

    public void outAParametro(AParametro node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParametro(AParametro node)
    {
        inAParametro(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        outAParametro(node);
    }

    public void inAFechadoComando(AFechadoComando node)
    {
        defaultIn(node);
    }

    public void outAFechadoComando(AFechadoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFechadoComando(AFechadoComando node)
    {
        inAFechadoComando(node);
        if(node.getComandoFechado() != null)
        {
            node.getComandoFechado().apply(this);
        }
        outAFechadoComando(node);
    }

    public void inAAbertoComando(AAbertoComando node)
    {
        defaultIn(node);
    }

    public void outAAbertoComando(AAbertoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAbertoComando(AAbertoComando node)
    {
        inAAbertoComando(node);
        if(node.getComandoAberto() != null)
        {
            node.getComandoAberto().apply(this);
        }
        outAAbertoComando(node);
    }

    public void inACondicionalElseComandoFechado(ACondicionalElseComandoFechado node)
    {
        defaultIn(node);
    }

    public void outACondicionalElseComandoFechado(ACondicionalElseComandoFechado node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACondicionalElseComandoFechado(ACondicionalElseComandoFechado node)
    {
        inACondicionalElseComandoFechado(node);
        if(node.getComandoElse() != null)
        {
            node.getComandoElse().apply(this);
        }
        if(node.getOtherwise() != null)
        {
            node.getOtherwise().apply(this);
        }
        if(node.getComandoIf() != null)
        {
            node.getComandoIf().apply(this);
        }
        if(node.getParenteseDir() != null)
        {
            node.getParenteseDir().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getParenteseEsq() != null)
        {
            node.getParenteseEsq().apply(this);
        }
        if(node.getInCaseThat() != null)
        {
            node.getInCaseThat().apply(this);
        }
        outACondicionalElseComandoFechado(node);
    }

    public void inALacoComandoFechado(ALacoComandoFechado node)
    {
        defaultIn(node);
    }

    public void outALacoComandoFechado(ALacoComandoFechado node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALacoComandoFechado(ALacoComandoFechado node)
    {
        inALacoComandoFechado(node);
        if(node.getComandoFechado() != null)
        {
            node.getComandoFechado().apply(this);
        }
        if(node.getParenteseDir() != null)
        {
            node.getParenteseDir().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getParenteseEsq() != null)
        {
            node.getParenteseEsq().apply(this);
        }
        if(node.getAsLongAs() != null)
        {
            node.getAsLongAs().apply(this);
        }
        outALacoComandoFechado(node);
    }

    public void inAAtribuicaoComandoFechado(AAtribuicaoComandoFechado node)
    {
        defaultIn(node);
    }

    public void outAAtribuicaoComandoFechado(AAtribuicaoComandoFechado node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAtribuicaoComandoFechado(AAtribuicaoComandoFechado node)
    {
        inAAtribuicaoComandoFechado(node);
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getAtribuicao() != null)
        {
            node.getAtribuicao().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAAtribuicaoComandoFechado(node);
    }

    public void inAAtribuicaoObjComandoFechado(AAtribuicaoObjComandoFechado node)
    {
        defaultIn(node);
    }

    public void outAAtribuicaoObjComandoFechado(AAtribuicaoObjComandoFechado node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAtribuicaoObjComandoFechado(AAtribuicaoObjComandoFechado node)
    {
        inAAtribuicaoObjComandoFechado(node);
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getAtribuicao() != null)
        {
            node.getAtribuicao().apply(this);
        }
        if(node.getAcesso() != null)
        {
            node.getAcesso().apply(this);
        }
        outAAtribuicaoObjComandoFechado(node);
    }

    public void inABlocoComandoFechado(ABlocoComandoFechado node)
    {
        defaultIn(node);
    }

    public void outABlocoComandoFechado(ABlocoComandoFechado node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlocoComandoFechado(ABlocoComandoFechado node)
    {
        inABlocoComandoFechado(node);
        if(node.getBloco() != null)
        {
            node.getBloco().apply(this);
        }
        outABlocoComandoFechado(node);
    }

    public void inAChamadaComandoFechado(AChamadaComandoFechado node)
    {
        defaultIn(node);
    }

    public void outAChamadaComandoFechado(AChamadaComandoFechado node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAChamadaComandoFechado(AChamadaComandoFechado node)
    {
        inAChamadaComandoFechado(node);
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        if(node.getChamada() != null)
        {
            node.getChamada().apply(this);
        }
        outAChamadaComandoFechado(node);
    }

    public void inACondicionalComandoAberto(ACondicionalComandoAberto node)
    {
        defaultIn(node);
    }

    public void outACondicionalComandoAberto(ACondicionalComandoAberto node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACondicionalComandoAberto(ACondicionalComandoAberto node)
    {
        inACondicionalComandoAberto(node);
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        if(node.getParenteseDir() != null)
        {
            node.getParenteseDir().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getParenteseEsq() != null)
        {
            node.getParenteseEsq().apply(this);
        }
        if(node.getInCaseThat() != null)
        {
            node.getInCaseThat().apply(this);
        }
        outACondicionalComandoAberto(node);
    }

    public void inACondicionalElseComandoAberto(ACondicionalElseComandoAberto node)
    {
        defaultIn(node);
    }

    public void outACondicionalElseComandoAberto(ACondicionalElseComandoAberto node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACondicionalElseComandoAberto(ACondicionalElseComandoAberto node)
    {
        inACondicionalElseComandoAberto(node);
        if(node.getComandoElse() != null)
        {
            node.getComandoElse().apply(this);
        }
        if(node.getOtherwise() != null)
        {
            node.getOtherwise().apply(this);
        }
        if(node.getComandoIf() != null)
        {
            node.getComandoIf().apply(this);
        }
        if(node.getParenteseDir() != null)
        {
            node.getParenteseDir().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getParenteseEsq() != null)
        {
            node.getParenteseEsq().apply(this);
        }
        if(node.getInCaseThat() != null)
        {
            node.getInCaseThat().apply(this);
        }
        outACondicionalElseComandoAberto(node);
    }

    public void inALacoComandoAberto(ALacoComandoAberto node)
    {
        defaultIn(node);
    }

    public void outALacoComandoAberto(ALacoComandoAberto node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALacoComandoAberto(ALacoComandoAberto node)
    {
        inALacoComandoAberto(node);
        if(node.getComandoAberto() != null)
        {
            node.getComandoAberto().apply(this);
        }
        if(node.getParenteseDir() != null)
        {
            node.getParenteseDir().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getParenteseEsq() != null)
        {
            node.getParenteseEsq().apply(this);
        }
        if(node.getAsLongAs() != null)
        {
            node.getAsLongAs().apply(this);
        }
        outALacoComandoAberto(node);
    }

    public void inABloco(ABloco node)
    {
        defaultIn(node);
    }

    public void outABloco(ABloco node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABloco(ABloco node)
    {
        inABloco(node);
        if(node.getFinishBlock() != null)
        {
            node.getFinishBlock().apply(this);
        }
        if(node.getListaComandos() != null)
        {
            node.getListaComandos().apply(this);
        }
        if(node.getAtributos() != null)
        {
            node.getAtributos().apply(this);
        }
        if(node.getStartBlock() != null)
        {
            node.getStartBlock().apply(this);
        }
        outABloco(node);
    }

    public void inAListaComandos(AListaComandos node)
    {
        defaultIn(node);
    }

    public void outAListaComandos(AListaComandos node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListaComandos(AListaComandos node)
    {
        inAListaComandos(node);
        {
            List<PComando> copy = new ArrayList<PComando>(node.getComando());
            Collections.reverse(copy);
            for(PComando e : copy)
            {
                e.apply(this);
            }
        }
        outAListaComandos(node);
    }

    public void inAChamada(AChamada node)
    {
        defaultIn(node);
    }

    public void outAChamada(AChamada node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAChamada(AChamada node)
    {
        inAChamada(node);
        if(node.getColcheteDir() != null)
        {
            node.getColcheteDir().apply(this);
        }
        if(node.getListaExp() != null)
        {
            node.getListaExp().apply(this);
        }
        if(node.getColcheteEsq() != null)
        {
            node.getColcheteEsq().apply(this);
        }
        {
            List<PAcessoExtra> copy = new ArrayList<PAcessoExtra>(node.getAcessoExtra());
            Collections.reverse(copy);
            for(PAcessoExtra e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAChamada(node);
    }

    public void inAListaExp(AListaExp node)
    {
        defaultIn(node);
    }

    public void outAListaExp(AListaExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListaExp(AListaExp node)
    {
        inAListaExp(node);
        {
            List<PExpExtra> copy = new ArrayList<PExpExtra>(node.getExpExtra());
            Collections.reverse(copy);
            for(PExpExtra e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAListaExp(node);
    }

    public void inAExpExtra(AExpExtra node)
    {
        defaultIn(node);
    }

    public void outAExpExtra(AExpExtra node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpExtra(AExpExtra node)
    {
        inAExpExtra(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getPipe() != null)
        {
            node.getPipe().apply(this);
        }
        outAExpExtra(node);
    }

    public void inAAcessoExtra(AAcessoExtra node)
    {
        defaultIn(node);
    }

    public void outAAcessoExtra(AAcessoExtra node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAcessoExtra(AAcessoExtra node)
    {
        inAAcessoExtra(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getSetaAcesso() != null)
        {
            node.getSetaAcesso().apply(this);
        }
        outAAcessoExtra(node);
    }

    public void inAAcesso(AAcesso node)
    {
        defaultIn(node);
    }

    public void outAAcesso(AAcesso node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAcesso(AAcesso node)
    {
        inAAcesso(node);
        {
            List<PAcessoExtra> copy = new ArrayList<PAcessoExtra>(node.getAcessoExtra());
            Collections.reverse(copy);
            for(PAcessoExtra e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAAcesso(node);
    }

    public void inABlocoExp(ABlocoExp node)
    {
        defaultIn(node);
    }

    public void outABlocoExp(ABlocoExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlocoExp(ABlocoExp node)
    {
        inABlocoExp(node);
        if(node.getFinishBlock() != null)
        {
            node.getFinishBlock().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getAtributos() != null)
        {
            node.getAtributos().apply(this);
        }
        if(node.getStartBlock() != null)
        {
            node.getStartBlock().apply(this);
        }
        outABlocoExp(node);
    }

    public void inATernarioExp(ATernarioExp node)
    {
        defaultIn(node);
    }

    public void outATernarioExp(ATernarioExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATernarioExp(ATernarioExp node)
    {
        inATernarioExp(node);
        if(node.getExpElse() != null)
        {
            node.getExpElse().apply(this);
        }
        if(node.getElse() != null)
        {
            node.getElse().apply(this);
        }
        if(node.getExpIf() != null)
        {
            node.getExpIf().apply(this);
        }
        if(node.getParenteseDir() != null)
        {
            node.getParenteseDir().apply(this);
        }
        if(node.getCondicao() != null)
        {
            node.getCondicao().apply(this);
        }
        if(node.getParenteseEsq() != null)
        {
            node.getParenteseEsq().apply(this);
        }
        if(node.getIf() != null)
        {
            node.getIf().apply(this);
        }
        outATernarioExp(node);
    }

    public void inAOrExp(AOrExp node)
    {
        defaultIn(node);
    }

    public void outAOrExp(AOrExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOrExp(AOrExp node)
    {
        inAOrExp(node);
        if(node.getExpOr() != null)
        {
            node.getExpOr().apply(this);
        }
        outAOrExp(node);
    }

    public void inAOrExpOr(AOrExpOr node)
    {
        defaultIn(node);
    }

    public void outAOrExpOr(AOrExpOr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOrExpOr(AOrExpOr node)
    {
        inAOrExpOr(node);
        if(node.getExpAnd() != null)
        {
            node.getExpAnd().apply(this);
        }
        if(node.getOuLogico() != null)
        {
            node.getOuLogico().apply(this);
        }
        if(node.getExpOr() != null)
        {
            node.getExpOr().apply(this);
        }
        outAOrExpOr(node);
    }

    public void inAAndExpOr(AAndExpOr node)
    {
        defaultIn(node);
    }

    public void outAAndExpOr(AAndExpOr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAndExpOr(AAndExpOr node)
    {
        inAAndExpOr(node);
        if(node.getExpAnd() != null)
        {
            node.getExpAnd().apply(this);
        }
        outAAndExpOr(node);
    }

    public void inAAndExpAnd(AAndExpAnd node)
    {
        defaultIn(node);
    }

    public void outAAndExpAnd(AAndExpAnd node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAndExpAnd(AAndExpAnd node)
    {
        inAAndExpAnd(node);
        if(node.getExpIgual() != null)
        {
            node.getExpIgual().apply(this);
        }
        if(node.getELogico() != null)
        {
            node.getELogico().apply(this);
        }
        if(node.getExpAnd() != null)
        {
            node.getExpAnd().apply(this);
        }
        outAAndExpAnd(node);
    }

    public void inAIgualExpAnd(AIgualExpAnd node)
    {
        defaultIn(node);
    }

    public void outAIgualExpAnd(AIgualExpAnd node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIgualExpAnd(AIgualExpAnd node)
    {
        inAIgualExpAnd(node);
        if(node.getExpIgual() != null)
        {
            node.getExpIgual().apply(this);
        }
        outAIgualExpAnd(node);
    }

    public void inAIgualExpIgual(AIgualExpIgual node)
    {
        defaultIn(node);
    }

    public void outAIgualExpIgual(AIgualExpIgual node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIgualExpIgual(AIgualExpIgual node)
    {
        inAIgualExpIgual(node);
        if(node.getExpRelacional() != null)
        {
            node.getExpRelacional().apply(this);
        }
        if(node.getIgual() != null)
        {
            node.getIgual().apply(this);
        }
        if(node.getExpIgual() != null)
        {
            node.getExpIgual().apply(this);
        }
        outAIgualExpIgual(node);
    }

    public void inARelacionalExpIgual(ARelacionalExpIgual node)
    {
        defaultIn(node);
    }

    public void outARelacionalExpIgual(ARelacionalExpIgual node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARelacionalExpIgual(ARelacionalExpIgual node)
    {
        inARelacionalExpIgual(node);
        if(node.getExpRelacional() != null)
        {
            node.getExpRelacional().apply(this);
        }
        outARelacionalExpIgual(node);
    }

    public void inAMenorExpRelacional(AMenorExpRelacional node)
    {
        defaultIn(node);
    }

    public void outAMenorExpRelacional(AMenorExpRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenorExpRelacional(AMenorExpRelacional node)
    {
        inAMenorExpRelacional(node);
        if(node.getExpSoma() != null)
        {
            node.getExpSoma().apply(this);
        }
        if(node.getMenorQue() != null)
        {
            node.getMenorQue().apply(this);
        }
        if(node.getExpRelacional() != null)
        {
            node.getExpRelacional().apply(this);
        }
        outAMenorExpRelacional(node);
    }

    public void inAMaiorExpRelacional(AMaiorExpRelacional node)
    {
        defaultIn(node);
    }

    public void outAMaiorExpRelacional(AMaiorExpRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMaiorExpRelacional(AMaiorExpRelacional node)
    {
        inAMaiorExpRelacional(node);
        if(node.getExpSoma() != null)
        {
            node.getExpSoma().apply(this);
        }
        if(node.getMaiorQue() != null)
        {
            node.getMaiorQue().apply(this);
        }
        if(node.getExpRelacional() != null)
        {
            node.getExpRelacional().apply(this);
        }
        outAMaiorExpRelacional(node);
    }

    public void inASomaExpRelacional(ASomaExpRelacional node)
    {
        defaultIn(node);
    }

    public void outASomaExpRelacional(ASomaExpRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASomaExpRelacional(ASomaExpRelacional node)
    {
        inASomaExpRelacional(node);
        if(node.getExpSoma() != null)
        {
            node.getExpSoma().apply(this);
        }
        outASomaExpRelacional(node);
    }

    public void inASomaExpSoma(ASomaExpSoma node)
    {
        defaultIn(node);
    }

    public void outASomaExpSoma(ASomaExpSoma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASomaExpSoma(ASomaExpSoma node)
    {
        inASomaExpSoma(node);
        if(node.getExpMult() != null)
        {
            node.getExpMult().apply(this);
        }
        if(node.getSoma() != null)
        {
            node.getSoma().apply(this);
        }
        if(node.getExpSoma() != null)
        {
            node.getExpSoma().apply(this);
        }
        outASomaExpSoma(node);
    }

    public void inASubtracaoExpSoma(ASubtracaoExpSoma node)
    {
        defaultIn(node);
    }

    public void outASubtracaoExpSoma(ASubtracaoExpSoma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASubtracaoExpSoma(ASubtracaoExpSoma node)
    {
        inASubtracaoExpSoma(node);
        if(node.getExpMult() != null)
        {
            node.getExpMult().apply(this);
        }
        if(node.getSubtracao() != null)
        {
            node.getSubtracao().apply(this);
        }
        if(node.getExpSoma() != null)
        {
            node.getExpSoma().apply(this);
        }
        outASubtracaoExpSoma(node);
    }

    public void inAMultExpSoma(AMultExpSoma node)
    {
        defaultIn(node);
    }

    public void outAMultExpSoma(AMultExpSoma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultExpSoma(AMultExpSoma node)
    {
        inAMultExpSoma(node);
        if(node.getExpMult() != null)
        {
            node.getExpMult().apply(this);
        }
        outAMultExpSoma(node);
    }

    public void inAMultExpMult(AMultExpMult node)
    {
        defaultIn(node);
    }

    public void outAMultExpMult(AMultExpMult node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultExpMult(AMultExpMult node)
    {
        inAMultExpMult(node);
        if(node.getExpUnaria() != null)
        {
            node.getExpUnaria().apply(this);
        }
        if(node.getMultiplicacao() != null)
        {
            node.getMultiplicacao().apply(this);
        }
        if(node.getExpMult() != null)
        {
            node.getExpMult().apply(this);
        }
        outAMultExpMult(node);
    }

    public void inADivisaoExpMult(ADivisaoExpMult node)
    {
        defaultIn(node);
    }

    public void outADivisaoExpMult(ADivisaoExpMult node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADivisaoExpMult(ADivisaoExpMult node)
    {
        inADivisaoExpMult(node);
        if(node.getExpUnaria() != null)
        {
            node.getExpUnaria().apply(this);
        }
        if(node.getDivisao() != null)
        {
            node.getDivisao().apply(this);
        }
        if(node.getExpMult() != null)
        {
            node.getExpMult().apply(this);
        }
        outADivisaoExpMult(node);
    }

    public void inAUnariaExpMult(AUnariaExpMult node)
    {
        defaultIn(node);
    }

    public void outAUnariaExpMult(AUnariaExpMult node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnariaExpMult(AUnariaExpMult node)
    {
        inAUnariaExpMult(node);
        if(node.getExpUnaria() != null)
        {
            node.getExpUnaria().apply(this);
        }
        outAUnariaExpMult(node);
    }

    public void inANegacaoExpUnaria(ANegacaoExpUnaria node)
    {
        defaultIn(node);
    }

    public void outANegacaoExpUnaria(ANegacaoExpUnaria node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANegacaoExpUnaria(ANegacaoExpUnaria node)
    {
        inANegacaoExpUnaria(node);
        if(node.getExpUnaria() != null)
        {
            node.getExpUnaria().apply(this);
        }
        if(node.getNegacao() != null)
        {
            node.getNegacao().apply(this);
        }
        outANegacaoExpUnaria(node);
    }

    public void inANegativoExpUnaria(ANegativoExpUnaria node)
    {
        defaultIn(node);
    }

    public void outANegativoExpUnaria(ANegativoExpUnaria node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANegativoExpUnaria(ANegativoExpUnaria node)
    {
        inANegativoExpUnaria(node);
        if(node.getExpUnaria() != null)
        {
            node.getExpUnaria().apply(this);
        }
        if(node.getSubtracao() != null)
        {
            node.getSubtracao().apply(this);
        }
        outANegativoExpUnaria(node);
    }

    public void inATermoExpUnaria(ATermoExpUnaria node)
    {
        defaultIn(node);
    }

    public void outATermoExpUnaria(ATermoExpUnaria node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATermoExpUnaria(ATermoExpUnaria node)
    {
        inATermoExpUnaria(node);
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        outATermoExpUnaria(node);
    }

    public void inAInteiroTermo(AInteiroTermo node)
    {
        defaultIn(node);
    }

    public void outAInteiroTermo(AInteiroTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAInteiroTermo(AInteiroTermo node)
    {
        inAInteiroTermo(node);
        if(node.getValorInteiro() != null)
        {
            node.getValorInteiro().apply(this);
        }
        outAInteiroTermo(node);
    }

    public void inARealTermo(ARealTermo node)
    {
        defaultIn(node);
    }

    public void outARealTermo(ARealTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARealTermo(ARealTermo node)
    {
        inARealTermo(node);
        if(node.getValorReal() != null)
        {
            node.getValorReal().apply(this);
        }
        outARealTermo(node);
    }

    public void inAYesTermo(AYesTermo node)
    {
        defaultIn(node);
    }

    public void outAYesTermo(AYesTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAYesTermo(AYesTermo node)
    {
        inAYesTermo(node);
        if(node.getYes() != null)
        {
            node.getYes().apply(this);
        }
        outAYesTermo(node);
    }

    public void inANoTermo(ANoTermo node)
    {
        defaultIn(node);
    }

    public void outANoTermo(ANoTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANoTermo(ANoTermo node)
    {
        inANoTermo(node);
        if(node.getNo() != null)
        {
            node.getNo().apply(this);
        }
        outANoTermo(node);
    }

    public void inAIdTermo(AIdTermo node)
    {
        defaultIn(node);
    }

    public void outAIdTermo(AIdTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdTermo(AIdTermo node)
    {
        inAIdTermo(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAIdTermo(node);
    }

    public void inAAcessoTermo(AAcessoTermo node)
    {
        defaultIn(node);
    }

    public void outAAcessoTermo(AAcessoTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAcessoTermo(AAcessoTermo node)
    {
        inAAcessoTermo(node);
        if(node.getAcesso() != null)
        {
            node.getAcesso().apply(this);
        }
        outAAcessoTermo(node);
    }

    public void inAChamadaTermo(AChamadaTermo node)
    {
        defaultIn(node);
    }

    public void outAChamadaTermo(AChamadaTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAChamadaTermo(AChamadaTermo node)
    {
        inAChamadaTermo(node);
        if(node.getChamada() != null)
        {
            node.getChamada().apply(this);
        }
        outAChamadaTermo(node);
    }

    public void inABlocoTermo(ABlocoTermo node)
    {
        defaultIn(node);
    }

    public void outABlocoTermo(ABlocoTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlocoTermo(ABlocoTermo node)
    {
        inABlocoTermo(node);
        if(node.getBlocoExp() != null)
        {
            node.getBlocoExp().apply(this);
        }
        outABlocoTermo(node);
    }

    public void inAParentesesTermo(AParentesesTermo node)
    {
        defaultIn(node);
    }

    public void outAParentesesTermo(AParentesesTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParentesesTermo(AParentesesTermo node)
    {
        inAParentesesTermo(node);
        if(node.getParenteseDir() != null)
        {
            node.getParenteseDir().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getParenteseEsq() != null)
        {
            node.getParenteseEsq().apply(this);
        }
        outAParentesesTermo(node);
    }
}
