/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AAtribuicaoObjComando extends PComando
{
    private PAcesso _acesso_;
    private PExp _exp_;

    public AAtribuicaoObjComando()
    {
        // Constructor
    }

    public AAtribuicaoObjComando(
        @SuppressWarnings("hiding") PAcesso _acesso_,
        @SuppressWarnings("hiding") PExp _exp_)
    {
        // Constructor
        setAcesso(_acesso_);

        setExp(_exp_);

    }

    @Override
    public Object clone()
    {
        return new AAtribuicaoObjComando(
            cloneNode(this._acesso_),
            cloneNode(this._exp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAtribuicaoObjComando(this);
    }

    public PAcesso getAcesso()
    {
        return this._acesso_;
    }

    public void setAcesso(PAcesso node)
    {
        if(this._acesso_ != null)
        {
            this._acesso_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._acesso_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._acesso_)
            + toString(this._exp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._acesso_ == child)
        {
            this._acesso_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._acesso_ == oldChild)
        {
            setAcesso((PAcesso) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
