/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ATernarioExp extends PExp
{
    private PExp _condicao_;
    private PExp _expIf_;
    private PExp _expElse_;

    public ATernarioExp()
    {
        // Constructor
    }

    public ATernarioExp(
        @SuppressWarnings("hiding") PExp _condicao_,
        @SuppressWarnings("hiding") PExp _expIf_,
        @SuppressWarnings("hiding") PExp _expElse_)
    {
        // Constructor
        setCondicao(_condicao_);

        setExpIf(_expIf_);

        setExpElse(_expElse_);

    }

    @Override
    public Object clone()
    {
        return new ATernarioExp(
            cloneNode(this._condicao_),
            cloneNode(this._expIf_),
            cloneNode(this._expElse_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATernarioExp(this);
    }

    public PExp getCondicao()
    {
        return this._condicao_;
    }

    public void setCondicao(PExp node)
    {
        if(this._condicao_ != null)
        {
            this._condicao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._condicao_ = node;
    }

    public PExp getExpIf()
    {
        return this._expIf_;
    }

    public void setExpIf(PExp node)
    {
        if(this._expIf_ != null)
        {
            this._expIf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expIf_ = node;
    }

    public PExp getExpElse()
    {
        return this._expElse_;
    }

    public void setExpElse(PExp node)
    {
        if(this._expElse_ != null)
        {
            this._expElse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expElse_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._condicao_)
            + toString(this._expIf_)
            + toString(this._expElse_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._condicao_ == child)
        {
            this._condicao_ = null;
            return;
        }

        if(this._expIf_ == child)
        {
            this._expIf_ = null;
            return;
        }

        if(this._expElse_ == child)
        {
            this._expElse_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._condicao_ == oldChild)
        {
            setCondicao((PExp) newChild);
            return;
        }

        if(this._expIf_ == oldChild)
        {
            setExpIf((PExp) newChild);
            return;
        }

        if(this._expElse_ == oldChild)
        {
            setExpElse((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
