/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TFinishBlock extends Token
{
    public TFinishBlock()
    {
        super.setText("finish");
    }

    public TFinishBlock(int line, int pos)
    {
        super.setText("finish");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFinishBlock(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFinishBlock(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFinishBlock text.");
    }
}
