/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TStartBlock extends Token
{
    public TStartBlock()
    {
        super.setText("start");
    }

    public TStartBlock(int line, int pos)
    {
        super.setText("start");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TStartBlock(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTStartBlock(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TStartBlock text.");
    }
}
